ngageoint/opensphere-desktop

open-sphere-base/core/src/main/java/io/opensphere/core/pipeline/processor/PointSpriteProcessor.java
There's no ticket for this.  Further testing made it clear we need to ignore view changes that don't significantly change the heading as it pertains to icon rotation.  That's what this fix does.
=> Performance improvement for icon rotation on view change

open-sphere-plugins/mapbox/src/main/java/io/opensphere/mapbox/server/MapboxServerSourceController.java
Adding support for Mapbox servers to the server cancel load button. 
The button is now functional for ArcGIS and Mapbox servers.
=> VORTEX-5526: Cancel server loading (Mapbox support)

open-sphere-base/mantle/src/main/java/io/opensphere/mantle/plugin/selection/SelectionHandler.java, open-sphere-plugins/my-places/src/main/java/io/opensphere/myplaces/controllers/MyPlacesController.java, open-sphere-plugins/my-places/src/main/java/io/opensphere/myplaces/controllers/RoiContextMenuProvider.java, open-sphere-plugins/my-places/src/main/java/io/opensphere/myplaces/specific/MyPointsMenuItemProvider.java
Load / add from a single polygon in the layer manager. Purge from a single polygon in the layer manager (would remove all query results that exist within the bounds of the polygon)
=>  Spatial query using a single area (ROI) from layer manager

open-sphere-base/control-panels/src/main/java/io/opensphere/controlpanels/about/AboutPanel.java, open-sphere-base/control-panels/src/main/java/io/opensphere/controlpanels/about/AboutUtil.java, open-sphere-plugins/imagery/src/main/java/io/opensphere/imagery/ImagerySourceGroup.java
- Adds `export logs` button to About dialog, which automatically zips all logs, preference files, and databases to a directory of the user's choice; containing directory will automatically open after the save operation
- Removes duplicated `more` button
- Extracts code to open directory for reuse in other methods
- Fixes escaping bug in the directory `open` buttons
- `ProcessBuilder` automatically quotes command inputs
- Escaped quotes in the command or flags are treated as literal quotes, so they won't be handled properly (often will cause the command to not run)
=> VORTEX-5596 : Log/Preference Zip Export

open-sphere-base/mantle/src/main/java/io/opensphere/mantle/data/geom/style/labelcontroller/LabelHoverController.java
Fix NullPointerException when attempting to draw labels for features that do not yet have a style class. Don't attempt to draw labels if the style class is null.
=> Fix Label NullPointerException

open-sphere-base/core/src/main/java/io/opensphere/core/datafilter/impl/DataFilterRegistryImpl.java, open-sphere-base/core/src/main/java/io/opensphere/core/terrain/ImmutableTriangleGlobeModel.java
Fixes #5655: Buffering polygons for spatial filters to resolve complex polygons. 
- Buffer all spatial filters with a distance of zero, which draws an outline around complex polygons, resolving overlap issues. 
- Update catch log message to actually grab the stack trace. 
-
=> VORTEX-5655: Buffering spatial filter areas to resolve complex polygons.

open-sphere-base/core/src/main/java/io/opensphere/core/net/NetworkConfigurationOptionsProvider.java, open-sphere-base/core/src/main/java/io/opensphere/core/net/config/ManualProxyConfiguration.java, open-sphere-base/core/src/main/java/io/opensphere/core/net/config/ProxyConfigurationMigrator.java, open-sphere-base/core/src/main/java/io/opensphere/core/net/config/ProxyConfigurations.java, open-sphere-base/core/src/main/java/io/opensphere/core/net/config/SystemProxyConfiguration.java, open-sphere-base/core/src/main/java/io/opensphere/core/net/config/UrlProxyConfiguration.java, open-sphere-base/core/src/main/resources/META-INF/services/io.opensphere.core.appl.PreConfigurationUpdateModule, open-sphere-base/core/src/main/resources/prefs/io.opensphere.core.net.NetworkConfigurationManagerImpl.xml, open-sphere-base/core/src/test/java/io/opensphere/core/net/config/ProxyConfigurationMigratorTest.java
Added migrator for old proxy configuration format to new proxy configurations format.
Fixed bug where exclusions for system/manual proxy were not being cleared.
Made proxy configurations readable for preference printing purposes.
Added tests for logic to convert the old preferences to new.
=> VORTEX-5659: Proxy configuration migrator

open-sphere-plugins/search/src/main/java/io/opensphere/search/SearchResultHudDialog.java, open-sphere-plugins/search/src/main/java/io/opensphere/search/view/MetadataPane.java
- Various formatting updates.
- Add a button to the search result dialog that clears the search.
- Does not clear the search text, so retrying the search is easy.
- Search window size expanded so that text fits without truncating.
=> VORTEX-5679 add clear button to search results dialog

open-sphere-base/core/src/main/java/io/opensphere/core/util/swing/binding/TextField.java
Fixes VORTEX-5705
- TextField was listening only for change events, not insert or remove events, causing any bound components to not be notified of user input.
=> VORTEX-5705: Text Field not responding to all events.

open-sphere-plugins/merge/src/main/java/io/opensphere/merge/algorithm/JoinData.java, open-sphere-plugins/merge/src/main/java/io/opensphere/merge/ui/JoinGui.java
- Do not use TreeMap and TreeSet if a specific order matters
- Related: VORTEX-5695
=> Fix Joins - Cache Exception

eclipse/open-sphere-dictionary.txt, open-sphere-base/core/src/main/java/io/opensphere/core/util/net/UrlUtilities.java, open-sphere-plugins/arcgis/src/main/java/io/opensphere/arcgis2/envoy/ArcGISLayerListEnvoy.java, open-sphere-plugins/arcgis/src/main/java/io/opensphere/arcgis2/mantle/ArcGISLayerProvider.java, open-sphere-plugins/arcgis/src/test/java/io/opensphere/arcgis2/envoy/ArcGISLayerListEnvoyTest.java
Fixes VORTEX-5682: ArcGIS URLs that include a layer don't show up in Add Data
- Updated handling of ArcGIS servers to introspect the URL, and treat anything beyond "rest/services" as a subpath
- Subpaths are used to restrict the set of recursive HTTP calls to the Arc server so that only required items are requested.
=> Feature arcgis subpaths

open-sphere-plugins/arcgis/src/main/java/io/opensphere/arcgis2/envoy/ArcGISLayerListEnvoy.java
Fixed for ArcGIS servers - instead of warning the user when layers can't load because of exceptions, throw QueryException and let controller handle it like other cases (shows toast message about error and shows server as inactive/failed).
=> VORTEX-5717: Servers showing active even with bad connection - ArcGIS support

open-sphere-base/mantle/src/main/java/io/opensphere/mantle/data/geom/style/impl/AbstractLOBFeatureVisualizationStyle.java
- Fix: max arrow size correctly initialized to half the length, as opposed to 500k meters
=> VORTEX-5703 / Max lob arrow size

open-sphere-base/test-support/src/main/java/io/opensphere/core/JDependTest.java
removes lazymap because it doesn't work right
=> Maven Interpretation Failure

open-sphere-base/mantle/src/main/java/io/opensphere/mantle/data/geom/style/impl/ui/LengthSliderStyleParameterEditorPanel.java
- Fix: It's possible for the line length slider range to be backwards, which throws an exception and requires deleting the feature layer and pulling it back in.
=> LOB style loading

open-sphere-base/analysis/src/main/java/io/opensphere/analysis/table/functions/Average.java, open-sphere-base/analysis/src/main/java/io/opensphere/analysis/table/functions/ColumnFunction.java, open-sphere-base/analysis/src/main/java/io/opensphere/analysis/table/functions/ColumnFunctionRegistry.java, open-sphere-base/analysis/src/main/java/io/opensphere/analysis/table/functions/Difference.java, open-sphere-base/analysis/src/main/java/io/opensphere/analysis/table/functions/Product.java, open-sphere-base/analysis/src/main/java/io/opensphere/analysis/table/functions/Quotient.java, open-sphere-base/analysis/src/main/java/io/opensphere/analysis/table/functions/StringJoin.java, open-sphere-base/analysis/src/main/java/io/opensphere/analysis/table/functions/Sum.java, open-sphere-base/analysis/src/main/java/io/opensphere/analysis/table/renderers/ColumnFunctionTableCellRenderer.java, open-sphere-base/mantle/src/main/java/io/opensphere/mantle/data/dynmeta/impl/DynamicMetadataDataTypeControllerImpl.java
- **Fix**: Inability to modify custom columns via double-click (or single-click checkbox, if boolean)
- API update caused wrong MetadataDataTypeController access
- **Fix**: Calculated columns do not allow dynamic updates as data changes
- Now a function of column indices rather than values
- **Add**: The following column functions have been added
- _Sum_ - Computes the sum of two columns, using non-numeric columns as 0.0
- _Difference_ - Computes the difference between two columns, using the first column selected as the initial value and non-numeric columns as 0.0
- _Product_ - Computes the product of two columns, using non-numeric columns as 1.0
- _Quotient_ - Computes the quotient of two columns, using the first column selected as the dividend and non-numeric columns as 1.0
- _Average_ …
=> VORTEX-5719 : Streaming & Additional Functions for Custom Column

open-sphere-plugins/merge/.classpath, open-sphere-plugins/merge/src/main/java/io/opensphere/merge/MergePlugin.java, open-sphere-plugins/merge/src/main/java/io/opensphere/merge/controller/MetaDataInfoProvider.java
Fixes that by making sure the constructed MetaDataInfo actually has "original keys".
=> VORTEX-5612 : Adding custom columns to Merge feature layers kills the metadata

open-sphere-plugins/search/src/main/java/io/opensphere/search/controller/SelectedResultHandler.java
- **Fix**: View would often not correctly center on search results, instead moving so that they were in-view (no matter where that was)
- If the screen is too zoomed-out to center a point, it will still not snap to the center position
- Future update recommendation: Connect map ends so that it can infinitely scroll on the x-axis
- **Change**: 2D projection search snaps to given point rather than animate
=> VORTEX-5757 jump to search result not working (consistently)

open-sphere-plugins/my-places/src/main/java/io/opensphere/myplaces/controllers/MyPlacesDataGroupController.java, open-sphere-plugins/my-places/src/main/java/io/opensphere/myplaces/models/MyPlacesDataGroupInfo.java
Fixes #
- My-Places Tree is flattened when Group-By Z-Order. This retains the elements in the folder, but removes the sub folders when grouped this way. 
-
-
=> Group By Z-Order My-Places Flattend Tree

open-sphere-base/core/src/main/java/com/bitsys/common/http/client/SslConfig.java, open-sphere-base/core/src/main/resources/system.properties
After failing to load a default SSL context due to (x) issue, attempt to correct the resource load. Otherwise, fail instead of generating a context without a trust store.
=> Fix SSL context load.

open-sphere-install/open-sphere-install-panels/src/main/java/io/opensphere/installer/panels/jre/OpenSphereTargetPanel.java
If a user selects a non-letter drive, disable the Next button and display a warning.
=> VORTEX-5442 : Prevent network drive Windows install

open-sphere-base/mantle/src/main/java/io/opensphere/mantle/data/geom/style/labelcontroller/LabelHoverController.java
- **Fix**: Labels would not show on hover for certain feature sets.
- Server features, where the server had multiple data groups, would return null for `getDataGroupInfo`
- Adds a check to see if a DataTypeInfo exists & is visible to the user
=> VORTEX-5756 Fix labels not showing on hover

open-sphere-base/control-panels/src/main/java/io/opensphere/controlpanels/layers/activedata/LayerControlPanel.java, open-sphere-base/mantle/src/main/java/io/opensphere/mantle/controller/impl/DataGroupControllerImpl.java
- **Fix**: User-activated tile layers that depend on an external server will not work with the tile style window unless reloaded.
- **Fix**: Hold Level spinner will throw an exception if the tile level controller a layer is associated with does not have a max generation (-1).
=> VORTEX-5780 'Styles for Tiles' Button for Reference Layers Not Opening HUD

open-sphere-plugins/heatmap/src/main/java/io/opensphere/heatmap/HeatmapTransformer.java
Fixes #133: Unable to create timeless heatmaps
- Avoid using constraints if the source data for the heatmap are all timeless.
=> VORTEX-5802 Fixing bug preventing the rendering of timeless heatmaps.

open-sphere-base/control-panels/src/main/java/io/opensphere/controlpanels/layers/activedata/controller/ActiveDataMouseListener.java, open-sphere-base/core/src/main/java/io/opensphere/core/model/GeographicBoundingBox.java, open-sphere-base/mantle/src/main/java/io/opensphere/mantle/data/util/impl/DataTypeActionUtils.java, open-sphere-plugins/kml/src/main/java/io/opensphere/kml/mantle/controller/KMLMantleController.java, open-sphere-plugins/my-places/src/main/java/io/opensphere/myplaces/controllers/MyPlacesController.java, open-sphere-plugins/open-sensor-hub/src/main/java/io/opensphere/osh/model/OSHDataGroupInfoAssistant.java
Fixes #142 Unable to fly to on different data sources
- This was never implemented for some data sources (CSVs, specifically), implemented ability to calculate a minimum bounding box if none has previously been calculated, and fly to the box. This does not take time into account.
=> VORTEX-5805: Fixing fly-to issues for groups of points.

open-sphere-base/core/src/main/java/io/opensphere/core/control/ui/ToolbarManager.java, open-sphere-plugins/search/src/main/java/io/opensphere/search/SearchPlugin.java, open-sphere-plugins/search/src/main/java/io/opensphere/search/SearchResultHudDialog.java, open-sphere-plugins/search/src/main/resources/pluginLoader.xml
Fixes #149 View menu's "Search" option doesn't do anything.
- The search pane was being initialized with a width of zero, causing it to error out. Fixed to initialize with a default width. 
- Renamed references from "SearchGoto" to just "Search"
=> VORTEX-5779: Fixing search view menu popup.

open-sphere-plugins/csv/src/main/java/io/opensphere/csv/CSVFileHandler.java
Fixes #
- Remove source from controller if it fails to load.  This will allows another source with the same name to be loaded later
-
-
-
=> VORTEX-5816 Remove source during load failure (sphere)

open-sphere-base/control-panels/src/main/java/io/opensphere/controlpanels/layers/activedata/ActiveLayerControlPanel.java, open-sphere-base/mantle/src/main/java/io/opensphere/mantle/data/geom/style/dialog/MiniStylePanel.java, open-sphere-base/mantle/src/main/java/io/opensphere/mantle/data/geom/style/impl/ui/ComboBoxAndColorChooserEditorPanel.java, open-sphere-base/mantle/src/main/java/io/opensphere/mantle/data/geom/style/impl/ui/ComboBoxStyleParameterEditorPanel.java, open-sphere-base/mantle/src/main/java/io/opensphere/mantle/data/geom/style/impl/ui/FloatSliderStyleParameterEditorPanel.java, open-sphere-base/mantle/src/main/java/io/opensphere/mantle/data/geom/style/impl/ui/MultiComboBoxStyleTwoParameterEditorPanel.java, open-sphere-base/mantle/src/main/java/io/opensphere/mantle/data/geom/style/impl/ui/MultiComboEditor.java
Fixes VORTEX-5832
- **Add**: Internal scrollable frame inside `MiniStylePanel`, fixed height of 300 pixels when visible
- **Update**: Various style editor classes updated in an attempt to fix resize problem
- When active layer panel reaches specific minimum width (varies for each editor type) the style editors will expand vertically without reporting new size. This pushes sibling panels outside of the `MiniStylePanel` dimensions
- This issue was not fixed; may only be resolvable through complete rewrite. Is fully mitigated through allowing horizontal scroll in mini style panel, however
=> VORTEX-5832 Labels on mini style panel

open-sphere-plugins/merge/src/main/java/io/opensphere/merge/algorithm/MergeData.java, open-sphere-plugins/merge/src/main/java/io/opensphere/merge/controller/MetaDataInfoProvider.java
Fixes VORTEX-5614
- Fix: Columns and data are stored in-order
- Fix: Entries that have no data for a particular column are not skipped
=> VORTEX-5614 Merged Layer has no time field

open-sphere-base/core/src/main/java/io/opensphere/core/util/fx/JFXAlert.java, open-sphere-plugins/wfs/src/main/java/io/opensphere/wfs/gml311/GmlErrorHandler.java, open-sphere-plugins/wfs/src/main/java/io/opensphere/wfs/gml311/GmlExceptionReport.java
- Allow nulls to be passed to JFXAlert as button types (they don't do anything)
- Update GmlExceptionReport to allow multiple exceptions per report
=> VORTEX-5812 Country Border Exception

open-sphere-plugins/feature-actions/src/main/java/io/opensphere/featureactions/controller/FeatureActionsController.java, open-sphere-plugins/feature-actions/src/main/java/io/opensphere/featureactions/controller/StyleFactory.java
Fixes VORTEX-5886
- listener responds to default style updates
- point size in the new style will default to the default style size
=> Enable Custom Style affects feature action styles when enabled, but not when disabled

open-sphere-base/control-panels/src/main/java/io/opensphere/controlpanels/layers/activedata/ActiveLayerControlPanel.java, open-sphere-base/control-panels/src/main/java/io/opensphere/controlpanels/state/DisableStatesMenuProvider.java, open-sphere-base/control-panels/src/main/java/io/opensphere/controlpanels/state/StatePlugin.java, open-sphere-base/control-panels/src/main/java/io/opensphere/controlpanels/state/StateView.java, open-sphere-base/core/src/main/java/io/opensphere/core/util/swing/SplitButton.java
Made the "States" button more similar in look and functionality to web's "States" button.
Reordered state controls drop down to put the saved states on top and added a label to them.
Added in options to import state from file/url in drop down.
Took away state button's save state action and made it only open up the state controls drop down menu.
Renamed some options / added icons  / rewrote the tooltips to match web.
Rewrote the icon legend entry for the states button.
=> VORTEX-5898 Look and Feel Alignment: State button

open-sphere-base/core/src/main/resources/system.properties, open-sphere-base/overlay/src/main/resources/prefs/MenuItem.HUDOverlayControls.xml, open-sphere-base/overlay/src/main/resources/prefs/MenuItem.WorldMap.xml
Moves the prefs files controlling overlay/overlay controls visibility from a config location to the overlay project so that for all configurations, the map overlay and controls are visible by default.
=> VORTEX-5896 Overlay - Show map overlay and controls by default

open-sphere-base/mantle/src/main/java/io/opensphere/mantle/data/DataGroupInfo.java
Made a new context for areas, so that the export and disable menu options are not overridden(removed) for items in the layers panel
=> VORTEX-5944 Heatmap menu options missing

open-sphere-plugins/kml/src/main/java/io/opensphere/kml/mantle/controller/KMLGeometryBuilder.java
Temporary fix to allow polygons which are not buffered correctly and don't overlap to be shown.
=> VORTEX-5946 kml loading issue

open-sphere-base/mantle/src/main/java/io/opensphere/mantle/transformer/impl/PurgeByRegionCommandWorker.java
Fixes #5957
- Checks the datatype name to determine if it purges. If it starts with "Area", then it won't purge (avoids introducing weird dependencies)
-
-
=> VORTEX-5957: Updating purge to not remove areas

open-sphere-base/mantle/src/main/java/io/opensphere/mantle/plugin/selection/BufferRegionCreator.java, open-sphere-base/mantle/src/main/java/io/opensphere/mantle/plugin/selection/SelectionCommandFactory.java, open-sphere-base/mantle/src/main/java/io/opensphere/mantle/plugin/selection/SelectionHandler.java, open-sphere-base/mantle/src/main/java/io/opensphere/mantle/plugin/selection/impl/CreateBufferSelectedCommand.java, open-sphere-base/mantle/src/main/java/io/opensphere/mantle/toolbox/MantleToolboxImpl.java
Fixes #5961
- Allows a user to right click on a polygon on the map, and if that sub-polygon is a member of a multipolygon, can create a buffer for the whole multipolygon.
- Adds an option to create the buffer for only the selected sub-polygon.
-
=> VORTEX-5961: Creating buffers for multipolygons from the map.

open-sphere-base/core/src/main/java/io/opensphere/core/geometry/util/PolylineGeometryUtils.java, open-sphere-base/mantle/src/main/java/io/opensphere/mantle/plugin/selection/SelectionCommandFactory.java, open-sphere-base/mantle/src/main/java/io/opensphere/mantle/plugin/selection/impl/AddFeaturesCommand.java, open-sphere-base/mantle/src/main/java/io/opensphere/mantle/plugin/selection/impl/AddFeaturesCurrentFrame.java, open-sphere-base/mantle/src/main/java/io/opensphere/mantle/plugin/selection/impl/CreateBufferCommand.java, open-sphere-base/mantle/src/main/java/io/opensphere/mantle/plugin/selection/impl/CreateBufferSelectedCommand.java, open-sphere-base/mantle/src/main/java/io/opensphere/mantle/plugin/selection/impl/DeselectCommand.java, open-sphere-base/mantle/src/main/java/io/opensphere/mantle/plugin/selection/impl/LoadFeaturesCommand.java, open-sphere-base/mantle/src/main/java/io/opensphere/mantle/plugin/selection/impl/LoadFeaturesCurrentFrameCommand.java, open-sphere-base/mantle/src/main/java/io/opensphere/mantle/plugin/selection/impl/RemoveAllFeaturesCommand.java, open-sphere-base/mantle/src/main/java/io/opensphere/mantle/plugin/selection/impl/SelectCommand.java, open-sphere-base/mantle/src/main/java/io/opensphere/mantle/plugin/selection/impl/SelectExclusiveCommand.java, open-sphere-plugins/my-places/src/main/java/io/opensphere/myplaces/specific/tracks/TracksContextMenuProvider.java
Fixes VORTEX-5981
- Update track buffer generation to account for segments with only 2 identical coordinates 
- Update menu generation to work properly for selected items and selected segments for polylines
- Update menu generation to remove 'set units' submenu when right clicking on a track
- Update menu generation to add icons to all right click menu items when right clicking on a track.
=> VORTEX-5981: Fixing track menu items, menu item icon render size

open-sphere-base/mantle/src/main/java/io/opensphere/mantle/icon/impl/gui/IconChooserDialog.java
Fixes VORTEX-5983
- Icon chooser says close instead of cancel on main dialog
=> VORTEX-5983 Icon Manager close instead of cancel

open-sphere-base/mantle/src/main/java/io/opensphere/mantle/iconproject/model/PanelModel.java, open-sphere-base/mantle/src/main/java/io/opensphere/mantle/iconproject/panels/GridBuilder.java, open-sphere-base/mantle/src/main/java/io/opensphere/mantle/iconproject/panels/TopMenuBar.java
Fixes
- Can swap between original grid layout of icons and text-only list layout
=> Icon Manager Grid and List Style

open-sphere-base/mantle/src/main/java/io/opensphere/mantle/icon/IconRegistry.java, open-sphere-base/mantle/src/main/java/io/opensphere/mantle/icon/impl/gui/IconTreeBuilder.java, open-sphere-base/mantle/src/main/java/io/opensphere/mantle/iconproject/impl/ButtonBuilder.java, open-sphere-base/mantle/src/main/java/io/opensphere/mantle/iconproject/impl/IconPopupMenuImpl.java, open-sphere-base/mantle/src/main/java/io/opensphere/mantle/iconproject/impl/LabelMaker.java, open-sphere-base/mantle/src/main/java/io/opensphere/mantle/iconproject/impl/TreePopupMenuImpl.java, open-sphere-base/mantle/src/main/java/io/opensphere/mantle/iconproject/model/IconManagerPrefs.java, open-sphere-base/mantle/src/main/java/io/opensphere/mantle/iconproject/model/ImportProp.java, open-sphere-base/mantle/src/main/java/io/opensphere/mantle/iconproject/model/PanelModel.java, open-sphere-base/mantle/src/main/java/io/opensphere/mantle/iconproject/panels/AddIconPane.java, open-sphere-base/mantle/src/main/java/io/opensphere/mantle/iconproject/panels/CollectNamesPane.java, open-sphere-base/mantle/src/main/java/io/opensphere/mantle/iconproject/panels/GridBuilder.java, open-sphere-base/mantle/src/main/java/io/opensphere/mantle/iconproject/panels/IconCustomizerPane.java, open-sphere-base/mantle/src/main/java/io/opensphere/mantle/iconproject/panels/MainPanel.java, open-sphere-base/mantle/src/main/java/io/opensphere/mantle/iconproject/panels/SubCollectPane.java, open-sphere-base/mantle/src/main/java/io/opensphere/mantle/iconproject/panels/TopMenuBar.java, open-sphere-base/mantle/src/main/java/io/opensphere/mantle/iconproject/panels/TreeBuilder.java, open-sphere-base/mantle/src/main/java/io/opensphere/mantle/iconproject/view/AddIconDialog.java, open-sphere-base/mantle/src/main/java/io/opensphere/mantle/iconproject/view/IconCustomizerDialog.java, open-sphere-base/mantle/src/main/java/io/opensphere/mantle/iconproject/view/IconPopupMenu.java, open-sphere-base/mantle/src/main/java/io/opensphere/mantle/iconproject/view/IconProjDialog.java
Fixes
- icon names display correctly when underscores are in the name
- icon size feature disabled in list mode
- rollover text adjustment for icons, right click menu works on first click
- code cleanup to remove extraneous bits and make it easier to read
=> Icon Manager Small Adjustments/Cleanup

open-sphere-base/analysis/src/main/java/io/opensphere/analysis/listtool/model/DataElementProvider.java
Fixes #VORTEX-6007 
Occasionally data comes in without coordinates, specifically from KML documents, which causes some things to fail. 
- Fix analysis tools to be more defensive when map points do not have coordinates.
=> Feature hotfix kml missing coordinates

open-sphere-base/core/src/main/java/io/opensphere/core/server/HttpServer.java, open-sphere-base/core/src/main/java/io/opensphere/core/util/fx/JFXAlert.java, open-sphere-plugins/ogc-server/src/main/java/io/opensphere/server/serverprovider/http/HttpServerImpl.java, open-sphere-plugins/ogc-server/src/main/java/io/opensphere/server/serverprovider/http/requestors/DeleteRequestor.java, open-sphere-plugins/ogc-server/src/main/java/io/opensphere/server/serverprovider/http/requestors/DeleteRequestorImpl.java
Fixes #6009
- Adds support for submitting HTTP Delete requests with custom headers. 
- Fixes formatting issue in JFXAlert (unrelated but found it and fixed it anyway)
-
=> VORTEX-6009: Adding support for HTTP DELETE requests with custom headers

open-sphere-base/control-panels/src/main/java/io/opensphere/controlpanels/animation/state/LiveStateController.java, open-sphere-base/core/src/main/java/io/opensphere/core/appl/TimeManagerStateController.java
Fixes #6058
- Set default time setting to off when saving states
=> VORTEX-6058: Defaulting time to off when saving states

open-sphere-base/core/src/main/java/io/opensphere/core/util/fx/AutoSelectComboBox.java
Fixes #6084
- Fix type ahead in auto-select combo box to grab the selected item when the text in the editor is incomplete.
=> VORTEX-6084: Fixing type ahead on country border

open-sphere-base/mantle/src/main/java/io/opensphere/mantle/data/geom/style/impl/StyleUtils.java
Fixes #6111
- When a label's value is null, it was incorrectly using the word "null" instead of leaving it blank. Fixing this.
=> VORTEX-6111: Feature missing lables render wrong

open-sphere-base/control-panels/src/main/java/io/opensphere/controlpanels/animation/state/AnimationStateController.java, open-sphere-base/control-panels/src/main/java/io/opensphere/controlpanels/state/StateControllerImpl.java, open-sphere-base/control-panels/src/main/java/io/opensphere/controlpanels/state/StateImportController.java, open-sphere-base/control-panels/src/main/java/io/opensphere/controlpanels/state/StatePlugin.java
Fixes VORTEX-6098
- Importing states seems to work as intended, so no problem there
- State doesn't toggle multiple times between activated and deactivated when being loaded
- All states are deactivated upon application shutdown
- Animation state checks if current time exists for activation
=> VORTEX-6098 State Import

open-sphere-plugins/csv/src/main/java/io/opensphere/csv/CSVTypeInfoGenerator.java
- Fixes analysis tools breaking from non-spatial csv imports
- CSVs can be imported as UNKNOWN if they do not contain spatial headers
=>  VORTEX-6120 

open-sphere-base/mantle/src/main/java/io/opensphere/mantle/plugin/selection/BufferRegionCreator.java, open-sphere-base/mantle/src/main/java/io/opensphere/mantle/plugin/selection/SelectionHandler.java
Fixes #6036
- For multi-polygonal areas (e.g.: multiple islands), users should be able to create buffer regions, and using those buffer regions, execute a query.
=> VORTEX-6036: Using multi-polygons to query

open-sphere-base/control-panels/src/main/java/io/opensphere/controlpanels/layers/availabledata/AvailableDataTreeTableTreeCellRenderer.java, open-sphere-base/control-panels/src/main/java/io/opensphere/controlpanels/layers/util/ClockAndOrColorLabel.java
Fixes VORTEX-6075
- Icons in the add data menu are colored based off the data group they are assigned to
- Data groups with a single layer use the color of the layer for the icon
- Data groups with more than one layer but have tile render properties use the color from the properties
- Data groups that fall under neither default to white
=> VORTEX-6075 Add data window should color icons with layer colors.

open-sphere-plugins/feature-actions/src/main/java/io/opensphere/featureactions/editor/ui/DragDropHandler.java, open-sphere-plugins/feature-actions/src/main/java/io/opensphere/featureactions/editor/ui/SimpleFeatureActionEditorBinder.java
Fixes 297
- Fix drag and drop removing cells when not dropping onto another cell
- Fix drag and drop not respecting drag direction
- Dragging up will place _before_ a cell, dragging down will place _after_
- Fix drag and drop panes duplicating themselves somehow
- Fix pane names being null (not sure what causes) causing an exception and preventing their deletion
=> Feature Action Drag&Drop

open-sphere-base/mantle/src/main/java/io/opensphere/mantle/data/geom/style/impl/AbstractFeatureVisualizationStyle.java, open-sphere-base/mantle/src/main/java/io/opensphere/mantle/data/geom/style/impl/ui/AbstractStyleParameterEditorPanel.java, open-sphere-base/mantle/src/main/java/io/opensphere/mantle/data/geom/style/impl/ui/MultiComboEditor.java
Fixes VORTEX-6126
- When mini style panel resizes, create scrollable for labels if necessary
- `AbstractStyleParameterEditorPanel` has functionality for `PANE_SCROLL` boolean option in `PanelBuilder` that sets control panel as a `JScrollPane` instead
- Update code to not include a bunch of panels for no reason
=> VORTEX-6126

open-sphere-base/core/src/main/java/io/opensphere/core/animation/impl/DefaultContinuousAnimationPlan.java
Fixes VORTEX-6099
- If we cannot get the intersection between the limit window and the full animation span, end before the skip. Instances where this would happen:
- Time span ends immediately after skip
- Time span ends during skip
- Time span ends before skip, but not containing active span, and extension would place it inside the skip
=> VORTEX-6099 Skip span

open-sphere-base/analysis/src/main/java/io/opensphere/analysis/baseball/BaseballPanel.java
Fixes #VORTEX-6167
- Add ability to double-click the location area to copy coordinates.
=> Feature baseball copy coordinates

open-sphere-laf/open-sphere-dark-laf/src/main/java/io/opensphere/laf/dark/OpenSphereDarkLookAndFeel.java
Fixes
- The color of the text for disabled ToolTips is white instead of close-to black
=> ToolTip Text Color for Disabled Components

open-sphere-base/mantle/src/main/java/io/opensphere/mantle/icon/impl/IconRegistryImpl.java
Fixes #VORTEX-6176
- Loading initial icons on a background thread to prevent Mantle initialization from stalling.
=> VORTEX-6176: Loading initial icons on a background thread

open-sphere-base/core/src/main/java/io/opensphere/core/util/ColorUtilities.java, open-sphere-plugins/kml/src/main/java/io/opensphere/kml/common/util/KMLSpatialTemporalUtils.java
Fixes VORTEX-6186
- Adjust parsing logic to handle cases when only 6 digits of color information are present, assuming fully opaque colors in this case.
=> Updating support in KML parsing to handle 6 digit colors (assuming fully opaqueness)

open-sphere-base/control-panels/src/main/java/io/opensphere/controlpanels/layers/layerdetail/LayerDetailPanel.java
Fixes VORTEX-6187
- Don't hide the settings panel when the layer is deactivated.
=> VORTEX-6187: Fixing issue that removes settings panel from detail popup when layer is deactivated.

open-sphere-base/core/src/main/resources/system.properties
Fixes VORTEX-6226
- Plugin init timeout increased 5x to 5 minutes total
=> VORTEX-6226: Increase Plugin Init Timeout

open-sphere-base/mantle/src/main/java/io/opensphere/mantle/data/cache/impl/DynamicMetaDataListCodeGenerator.java
Fixes VORTEX-6238
- Times that fall under java.util.Time are now properly handled, and won't always give back null
=> VORTEX-6238: DATE_TIME Metadata does not appear

open-sphere-base/mantle/src/main/java/io/opensphere/mantle/data/geom/style/impl/ui/IconChooserStyleParameterEditorPanel.java, open-sphere-base/mantle/src/main/java/io/opensphere/mantle/icon/chooser/model/IconManagerPrefs.java, open-sphere-base/mantle/src/main/java/io/opensphere/mantle/icon/chooser/view/IconDialog.java, open-sphere-base/mantle/src/main/java/io/opensphere/mantle/icon/chooser/view/IconDialogSupplier.java
Fixes VORTEX-6246
- the last selected icon from the icon manager is saved so when the manager is opened later it starts with that icon already selected
=> VORTEX-6246

open-sphere-plugins/filter-builder/src/main/java/io/opensphere/filterbuilder/state/FilterManagerStateController.java
Fixes VORTEX-6200
- all filters are now assigned to a layer, and will not be attached to a state
=> VORTEX-6200: Filters don't load when importing a state file

open-sphere-base/core/src/main/java/io/opensphere/core/viewer/impl/Viewer3D.java, open-sphere-base/mantle/src/main/java/io/opensphere/mantle/icon/chooser/model/IconChooserModel.java
Fixes VORTEX-6249
- viewer is reset to the default position if, upon starting MIST, the viewer is inside terrain or is outside the maximum distance
- quick fix for putting the remove custom icon action on the JavaFX thread
=> VORTEX-6249: Tool crashes with invalid saved position

pom.xml
Fixes #Java 9 runtime issues - fixes illegal reflection of JAXB which was causing H2 database to delete on startup. 
-  Change JAXB API,IMP,WX versions to 2.3.1 
-  JAXB Core deprecated so kept at 2.3.0
-
=> update jaxb versions

open-sphere-base/mantle/src/main/java/io/opensphere/mantle/plugin/selection/SelectionCommandFactory.java
Removes the duplicate menu item "Deselect All"
- Delete the listener and menu item from being added twice. 
-
-
=> remove menu being added twice

open-sphere-plugins/csv-common/pom.xml, open-sphere-plugins/csv-common/src/main/java/io/opensphere/csvcommon/ui/controller/ImportableColumnController.java
Fixes # VORTEX-6247:Reordering CSV columns
Bug caused by duplicates of the Index and Color columns which must always exist.
- When user has these fields automatically re-name on import to prevent memory confusion.
- Retains user color & potential custom indexing.
---Could be modified to override our Index + Color with user; but may not neccessarily make sense to do so.
=> Ft csvPatch

open-sphere-base/core/src/main/java/io/opensphere/core/util/XMLUtilities.java
Fixes VORTEX-6183
- Whitespace filter has checks for if the field is only whitespace but is exactly a tab/space to help whitespace delimited files
=> VORTEX-6183 XML Reading Whitespace

open-sphere-base/mantle/src/main/java/io/opensphere/mantle/icon/chooser/view/IconDetail.java, open-sphere-base/mantle/src/main/java/io/opensphere/mantle/icon/chooser/view/SearchControlBar.java
Fixes VORTEX-6194
- delete icon button moved onto the icon canvas, next to the favorite button
- tooltips added to favorite button
=> VORTEX-6194 Move icon delete button into preview area

open-sphere-base/control-panels/src/main/java/io/opensphere/controlpanels/styles/model/StyleOptions.java, open-sphere-plugins/feature-actions/src/main/java/io/opensphere/featureactions/editor/ui/SimpleFeatureActionRowBinder.java
Fixes # VORTEX-6063
- when icons are enabled in feature actions, the color of the feature action is saved so it can be recovered later
- activating icons in a feature action disables the color selector and turns the color of the feature action to white so the icon doesn't get colored
=> VORTEX-6063 Coloring features from feature actions shades icon

open-sphere-base/test-support/src/main/java/io/opensphere/core/JDependTest.java
Fixes occasional testing error when jdeps is not available on the PATH variable by using the full path.
=> Updating JDependTest to use full jdeps path

open-sphere-plugins/csv-common/src/main/java/io/opensphere/csvcommon/detect/columnformat/ColumnDelimiterDetector.java
Fixes VORTEX-6292
- end of delimiter check doesn't only compares if previous character is the same as the current delimiter, instead of all potential delimiters
- updated regex to match the comments
=> VORTEX-6292 Desktop not parsing/importing csv correctly
