open-sphere-plugins/open-sensor-hub/src/main/java/io/opensphere/osh/mantle/OSHMantleController.java, open-sphere-plugins/open-sensor-hub/src/main/java/io/opensphere/osh/util/OSHQuerier.java
Adding support for OSH servers to the server cancel load button.
The button is now functional for ArcGIS, Mapbox, OGC, and OSH servers.
=> VORTEX-5526: Cancel server loading (OSH support)

open-sphere-plugins/my-places/src/main/java/io/opensphere/myplaces/util/PlacemarkUtils.java
ability to control the line size, opacity, and color of the track in the mini-style editor in the layer manager
=> VORTEX-5515: Ability to edit tracks

eclipse/open-sphere-dictionary.txt, open-sphere-base/mantle/src/main/java/io/opensphere/mantle/data/MetaDataInfo.java, open-sphere-base/mantle/src/main/java/io/opensphere/mantle/data/impl/DefaultMetaDataInfo.java
Adding a field to metadata to encapsulate the name of the unique identifier field into an observable field that can be bound to.
=> Feature live track settings

open-sphere-base/core/src/main/java/io/opensphere/core/pipeline/processor/TextureProcessor.java
When Icon Rotation is enabled, prevent selected icons from disappearing on the map.
=> Feature fix disappering icons

open-sphere-base/core/src/main/java/io/opensphere/core/control/ui/ToolbarManager.java, open-sphere-base/mantle/src/main/java/io/opensphere/mantle/data/geom/style/dialog/VisualizationStyleOptionsProvider.java
VORTEX-5591
- Enables `Show Toolbar Icon Labels` option by default.
- Adds `Show Toolbar Icon Labels` option to `Settings > Styles`
=> Feature - Toolbar Icon Labels Settings/Default

open-sphere-plugins/my-places/src/main/java/io/opensphere/myplaces/importer/DataElementTrackExporter.java, open-sphere-plugins/my-places/src/main/java/io/opensphere/myplaces/specific/tracks/TrackRenderer.java, open-sphere-plugins/my-places/src/main/java/io/opensphere/tracktool/model/TrackNode.java, open-sphere-plugins/my-places/src/main/java/io/opensphere/tracktool/model/impl/DefaultTrackNode.java, open-sphere-plugins/my-places/src/main/java/io/opensphere/tracktool/model/persist/v1/JAXBTrackNode.java, open-sphere-plugins/my-places/src/main/java/io/opensphere/tracktool/registry/TrackRegistry.java
added new param to DefaultTrackNode to pass the cacheID.
=> Add CacheID to DefaultTrackNode

open-sphere-plugins/my-places/src/main/java/io/opensphere/myplaces/controllers/RoiContextMenuProvider.java
A small bug where if a track gets added to MyPlaces, it was preventing menu options to appear.
=> MyPlaces context menu bug

open-sphere-base/control-panels/src/main/java/io/opensphere/controlpanels/about/AboutPanel.java, open-sphere-base/control-panels/src/main/java/io/opensphere/controlpanels/about/AboutUtil.java
- Include database file by boolean
- Default `false`
- Temporarily static value
=> Update / Disable DB export

open-sphere-base/analysis/src/main/resources/META-INF/services/io.opensphere.core.export.Exporter, open-sphere-plugins/heatmap/pom.xml, open-sphere-plugins/heatmap/project-checkstyle-suppressions.xml, open-sphere-plugins/heatmap/src/main/resources/META-INF/services/io.opensphere.core.export.Exporter
VORTEX-5414: Fixing exporter configuration.
=> Fixing build.

open-sphere-base/analysis/src/main/java/io/opensphere/analysis/listtool/model/ListToolTableModel.java
Missed isCellEditable update to exclude ColumnFunctions
=> VORTEX-5642 Update

open-sphere-base/mantle/src/main/java/io/opensphere/mantle/data/geom/style/impl/ui/IconChooserStyleParameterEditorPanel.java, open-sphere-base/mantle/src/main/java/io/opensphere/mantle/icon/impl/gui/IconChooserDialog.java
- Add: Message indicating a context menu exists.
- Fix: Some situations would result in the icon menu opening without a message showing.
=> VORTEX-5647 : Add help text to icon selection menu.

open-sphere-base/core/src/main/java/io/opensphere/core/pipeline/processor/LabelProcessor.java, open-sphere-base/mantle/src/main/java/io/opensphere/mantle/data/geom/style/labelcontroller/LabelHoverController.java
- Fix: Don't draw labels via hover if they're already on screen.
- Fix: LabelProcessor formatting.
=> Situationally draw labels.

open-sphere-base/control-panels/src/main/java/io/opensphere/controlpanels/layers/activedata/ActiveLayerControlPanel.java, open-sphere-plugins/my-places/src/main/java/io/opensphere/tracktool/model/impl/DefaultTrack.java
- Fix: ActiveLayerControlPanel selectedType can be null
- Fix: Track timespan can be null if a JAXBTrack; when null, can never be updated
- May be related to VORTEX-5585
- Fix: Formatting
=> Fix NullPointerException in tracks

open-sphere-base/mantle/src/main/java/io/opensphere/mantle/controller/AbstractIconLoader.java, open-sphere-base/mantle/src/main/java/io/opensphere/mantle/icon/impl/AbstractIconLoader.java, open-sphere-base/mantle/src/main/java/io/opensphere/mantle/icon/impl/FontIcons.java, open-sphere-base/mantle/src/main/java/io/opensphere/mantle/plugin/MantlePlugin.java, open-sphere-plugins/kml/src/main/java/io/opensphere/kml/KMLPlugin.java, open-sphere-plugins/kml/src/main/java/io/opensphere/kml/mantle/controller/KMLGeometryBuilder.java, open-sphere-plugins/kml/src/main/java/io/opensphere/kml/mantle/controller/KmlIcons.java
=> Fix circular reference issues.

open-sphere-base/core/src/main/java/io/opensphere/core/order/impl/OrderManagerImpl.java, open-sphere-base/core/src/main/java/io/opensphere/core/order/impl/config/v1/OrderManagerConfig.java
Fixed null pointer when moving changing z order of layers.
=> Feature Z-Order Null Pointer

open-sphere-base/core/.classpath, open-sphere-base/core/src/main/java/io/opensphere/core/options/impl/AbstractJFXOptionsProvider.java, open-sphere-base/core/src/main/java/io/opensphere/core/search/SearchResult.java
=> VORTEX-5677 Main window search geo results go back years

open-sphere-base/core/src/main/java/io/opensphere/core/projection/impl/EquirectangularProjection.java, open-sphere-base/core/src/main/java/io/opensphere/core/viewer/impl/DynamicViewer.java, open-sphere-base/core/src/main/java/io/opensphere/core/viewer/impl/Viewer2D.java, open-sphere-base/core/src/main/java/io/opensphere/core/viewer/impl/Viewer3D.java, open-sphere-base/core/src/main/java/io/opensphere/core/viewer/impl/ViewerAnimator.java, open-sphere-base/mantle/src/main/java/io/opensphere/mantle/data/util/impl/DataElementActionUtilsImpl.java, open-sphere-base/mantle/src/main/java/io/opensphere/mantle/data/util/impl/DataTypeActionUtils.java
Fixes #
Centering on a feature(s) works correctly in 2d mode ( Equirectangular ) .
-
-
-
=> VORTEX 5676 : Center on any item does not center on it.

open-sphere-plugins/my-places/src/main/java/io/opensphere/myplaces/controllers/RoiContextMenuProvider.java
Fixes #
- Context menu for points in myplaces was not working
-
-
=> Context menu for points in my places bug

open-sphere-plugins/merge/src/main/java/io/opensphere/merge/MergePlugin.java
=> VORTEX-5695 Merges not showing in Joins/Merges

open-sphere-plugins/merge/src/test/java/io/opensphere/merge/MergePluginTest.java
Merged a PR without realizing that the build was failing on this test - so here's the fix for it.
=> Test fix related to VORTEX-5695 work

open-sphere-plugins/merge/src/test/java/io/opensphere/merge/MergePluginTestDisplay.java
Renamed MergePluginTest -> MergePluginTestDisplay.
Build should succeed now.
=> Test fix related to VORTEX-5695 work - build fix

open-sphere-plugins/wfs/src/main/java/io/opensphere/wfs/state/activate/WFSDataTypeBuilder.java
=> VORTEX-5700 Loading States Broken

open-sphere-plugins/kml/src/main/java/io/opensphere/kml/common/model/KMLDataSource.java, open-sphere-plugins/kml/src/main/java/io/opensphere/kml/envoy/KMLProcessor.java
=> VORTEX-5677 Filter geo query results out of KML/map/analysis tools

open-sphere-base/mantle/src/main/java/io/opensphere/mantle/transformer/impl/worker/AbstractRenderPropertyUpdator.java
=> VORTEX-5684 Auto-color visibility bug with large sets of data

open-sphere-base/mantle/src/main/java/io/opensphere/mantle/transformer/impl/worker/AbstractRenderPropertyUpdator.java, open-sphere-base/mantle/src/main/java/io/opensphere/mantle/transformer/impl/worker/StyleBasedBuildAndPublishGeometriesWorker.java
=> Feature visibility bug

Jenkinsfile
- On any branch starting with the text "feature", skips the site and archive site steps.
=> Updating build to skip site for feature branches.

open-sphere-base/control-panels/src/main/java/io/opensphere/controlpanels/layers/activedata/ActiveDataPanel.java, open-sphere-base/control-panels/src/main/java/io/opensphere/controlpanels/layers/groupby/GroupByActiveZOrderTreeBuilder.java, open-sphere-base/core/src/main/java/io/opensphere/core/order/impl/DefaultOrderCategory.java, open-sphere-plugins/my-places/src/main/java/io/opensphere/myplaces/models/MyPlacesDataTypeInfo.java
Fixes #
- My Places now appear when grouping by Z-Order
- Template for adding drag-n-drop z-ordering to my places DataGroup now available.
-
=> VORTEX-5706: My Places Z-Order Not Appearing

open-sphere-base/core/.classpath, open-sphere-base/core/pom.xml, open-sphere-base/core/src/main/java/io/opensphere/core/common/connection/BasicAuthenticationConfiguration.java, open-sphere-base/core/src/main/java/io/opensphere/core/common/connection/ProxyConfiguration.java, pom.xml
- add apache-snapshots repository
- remove commons-httpclient
=> Remove commons3 httpclient. Add apache snapshot repo to pom.

Jenkinsfile
Fixes #
- Updated jenkins file to use Java 9
-
-
=> Updating JDK to 9 for Jenkins.

open-sphere-base/mantle/src/main/java/io/opensphere/mantle/crust/DataTypeChecker.java, open-sphere-plugins/feature-actions/src/main/java/io/opensphere/featureactions/editor/ui/FeatureActionsMenuProvider.java, open-sphere-plugins/merge/src/main/java/io/opensphere/merge/ui/AbstractMergeMergeContextMenuProvider.java, open-sphere-plugins/my-places/src/main/java/io/opensphere/myplaces/controllers/RoiContextMenuProvider.java
Fixes #
- Right clicking on a sub-folder brings up correct context menu.
- Ability to export specific sub-folders to different file types.
=> VORTEX-5489 : Export My Places Sub-Folders

open-sphere-base/test-support/src/main/java/io/opensphere/core/JDependTest.java
- Adds stack trace to JDependTest failures to better diagnose exceptional failures.
=> Adding stack trace to JDependTest failures.

open-sphere-base/test-support/src/main/java/io/opensphere/core/JDependTest.java, pom.xml
- Managed plugin dependencies for PMD plugin.
=> Feature test fixes

pom.xml
=> Fixing XJC for alternate JDK configurations.

open-sphere-plugins/arcgis/src/main/java/io/opensphere/arcgis2/envoy/ArcRestEnvoyUtils.java
Fixes #
- Replace any wildcards (*) from the arcgis feature id query with %
-
-
=> VORTEX-5464 : ArcGIS wildcard is % but we instruct users to use *

open-sphere-base/core/src/main/java/io/opensphere/core/control/action/MenuOption.java
=> Adding ability to associate an Icon with the MenuOption

open-sphere-base/mantle/src/main/java/io/opensphere/mantle/data/impl/DataGroupInfoGroupByUtility.java, open-sphere-plugins/my-places/src/main/java/io/opensphere/myplaces/controllers/MyPlacesDataGroupController.java, open-sphere-plugins/my-places/src/main/java/io/opensphere/myplaces/models/MyPlacesDataGroupInfo.java
Fixes #
- My Places DataTypes are all added under group by z-order correctly 
- 
-
=> Group-By Z-Order Adds Children Of Parent DataGroups

open-sphere-plugins/my-places/src/main/java/io/opensphere/myplaces/constants/ImportExportHeader.java, open-sphere-plugins/my-places/src/main/java/io/opensphere/myplaces/export/MyPlacesCsvExporter.java, open-sphere-plugins/my-places/src/main/java/io/opensphere/myplaces/importer/AbstractDataElementExporter.java, open-sphere-plugins/my-places/src/main/java/io/opensphere/myplaces/importer/DataElementTrackExporter.java, open-sphere-plugins/my-places/src/main/java/io/opensphere/myplaces/importer/MyPlacesCsvImporter.java, open-sphere-plugins/my-places/src/main/java/io/opensphere/myplaces/specific/points/PointMigrator.java, open-sphere-plugins/my-places/src/main/java/io/opensphere/myplaces/specific/points/renderercontrollers/CalloutDragger.java, open-sphere-plugins/my-places/src/main/java/io/opensphere/myplaces/specific/regions/utils/RegionUtils.java, open-sphere-plugins/my-places/src/main/java/io/opensphere/myplaces/specific/tracks/TrackDataElementsController.java, open-sphere-plugins/my-places/src/main/java/io/opensphere/myplaces/util/PlacemarkUtils.java, open-sphere-plugins/my-places/src/main/java/io/opensphere/tracktool/TrackArc.java
- TreeMaps provide speed but rely on natural-language ordering for entries
- A lot of the project requires specific ordering based on order-of-input
- LinkedHashMaps are better
=> Remove TreeMaps from my-places

open-sphere-base/core/src/main/java/io/opensphere/core/cache/jdbc/TypeMapper.java, open-sphere-base/core/src/main/java/io/opensphere/core/cache/jdbc/type/ObjectTranslator.java
Fix issue where timespan values inside property arrays would cause caching to fail. Described as part of `Loading KML file error`.
=> Timespan Caching Fix

open-sphere-base/mantle/src/main/java/io/opensphere/mantle/data/geom/style/dialog/VisualizationStyleDataTypePanel.java
=> Fix bad textarea formatting.

open-sphere-install/open-sphere-install-panels/pom.xml, open-sphere-install/open-sphere-install-panels/src/main/java/io/opensphere/installer/panels/jre/DirectoryWritableCondition.java, open-sphere-install/open-sphere-install-panels/src/main/java/io/opensphere/installer/panels/jre/JRELocatorHelper.java, open-sphere-install/open-sphere-install-panels/src/main/java/io/opensphere/installer/panels/jre/JRELocatorPanel.java, open-sphere-install/open-sphere-install-panels/src/main/java/io/opensphere/installer/panels/jre/OpenSphereTargetPanel.java
Fixes broken installer
- Remove external dependencies, as they were trivially used, and not being included correctly in the build. 
- Clean up other items in the install panels project.
=> Fixing installer bug.

open-sphere-base/xyz-tile/src/main/java/io/opensphere/xyztile/envoy/XYZTileEnvoy.java, open-sphere-plugins/open-street-map/src/main/java/io/opensphere/osm/server/OSMServerSourceController.java
Fixes #
Added a 'ping' capability to XYZTileEnvoy to determine server connection before the OSM models are added.
-
-
-
=> Feature osm false active

open-sphere-install/open-sphere-install-panels/src/main/java/io/opensphere/installer/panels/jre/OpenSphereTargetPanel.java
Fixes #131 Installer improperly fails check for network drive 
- The validation of installation to a network drive was failing. Fixed.
=> Feature netdrive fix

open-sphere-plugins/heatmap/src/main/java/io/opensphere/heatmap/HeatmapVisualizationStyle.java
Fixes VORTEX-5801
- Add tooltips to Heatmap mini style panel that describe what sliders are used for
- Add slider information to full style panel description
=> VORTEX-5801 Heatmap Intensity

open-sphere-plugins/csv-common/src/main/java/io/opensphere/csvcommon/parse/CsvProviderBase.java
Correctly finishes loading CSV files without data in them
=> VORTEX-5058 CSV with no data could be handled better

open-sphere-base/mantle/src/main/java/io/opensphere/mantle/icon/impl/gui/IconBuilderChoiceDialog.java
Add tree values that were forgotten.
=> Fix the icon builder

open-sphere-base/core/src/main/java/io/opensphere/core/appl/versions/view/AutoUpdateOptionsPanel.java
Fixes VORTEX-5817
- **Add**: Version buttons have listeners that actually do something.
=> VORTEX-5817 Version Fallback

open-sphere-base/control-panels/src/main/java/io/opensphere/controlpanels/layers/activedata/ActiveLayerControlPanel.java
Fixes VORTEX-5830
- **Add**: a close button
- **Update**: ActiveDataPanel refactor (private `get` -> build)
=> VORTEX-5830 Mini Style Panel Not Showing All layer Options

eclipse/open-sphere-formatter.xml, open-sphere-base/core/eclipse/formatter.xml, open-sphere-base/core/src/main/resources/system.properties, open-sphere-development-utilities/open-sphere-launcher-creator/src/main/java/io/opensphere/develop/util/launch/ProjectLauncherWriter.java, open-sphere-install/.classpath, open-sphere-install/open-sphere-izpack-configuration/src/main/resources/izpack/install.xml
- Updated references to Java 1.8 to Java 9
- Fixed the launcher creator to work with additional configurations
=> Fix launcher creator

open-sphere-base/mantle/src/main/java/io/opensphere/mantle/plugin/selection/SelectionCommand.java, open-sphere-base/mantle/src/main/java/io/opensphere/mantle/plugin/selection/SelectionHandler.java
Fixes #
- Refactored a hashmap to be an enum map since it was using enums as keys
- Ability to use functions in selection handler
-
=>  Create Buffer Region - Area Menu Action 

open-sphere-plugins/imagery/src/main/java/io/opensphere/imagery/ImagerySourceWizardPanel.java
Fixes #
- Removed 'Detail' Button
- Re-positioned warning to look better in absence of button
-
-
-
=> VORTEX-5804 Remove Detail Button Sphere

open-sphere-base/control-panels/src/main/java/io/opensphere/controlpanels/layers/util/FeatureTypeLabel.java, open-sphere-plugins/csv/src/main/java/io/opensphere/csv/CSVTypeInfoGenerator.java
Fixes #
- CSVs with no SPATIAL columns as a result of no data are now given MapVisualization anyway
=> VORTEX-5826 Feature layer icon showing as ? in the layers window

open-sphere-base/core/src/main/java/io/opensphere/core/util/swing/GenericFontIcon.java
=> Fixing menu icons

open-sphere-base/xyz-tile/src/main/java/io/opensphere/xyztile/envoy/XYZTileEnvoy.java, open-sphere-plugins/ogc-server/src/main/java/io/opensphere/server/manager/ServerManagerPanel.java
Fixes #
- Logging cleanup for server activiation
-
-
-
=> VORTEX-5726 Light cleanup of some server activiation code

open-sphere-base/mantle/src/main/java/io/opensphere/mantle/plugin/selection/BufferRegionCreator.java, open-sphere-base/mantle/src/main/java/io/opensphere/mantle/plugin/selection/BufferRegionImpl.java, open-sphere-base/mantle/src/main/java/io/opensphere/mantle/plugin/selection/SelectionHandler.java
Fixes #
- Re-factored Create Buffer region into separate class
- Select Create Buffer Menu through area context menu
-
=> Area's Create Buffer Region

open-sphere-base/mantle/src/main/java/io/opensphere/mantle/plugin/queryregion/QueryRegionManager.java, open-sphere-base/mantle/src/main/java/io/opensphere/mantle/plugin/queryregion/impl/QueryRegionManagerImpl.java
- Promotes methods to public and into the query region manager interface.
=> VORTEX-5854: Implementing Query add / load operations.

open-sphere-base/core/src/main/java/io/opensphere/core/util/image/ImageUtil.java, open-sphere-base/mantle/src/main/java/io/opensphere/mantle/icon/impl/gui/IconBuilderPane.java, open-sphere-base/mantle/src/main/java/io/opensphere/mantle/icon/impl/gui/IconChooserDialog.java, open-sphere-base/mantle/src/main/java/io/opensphere/mantle/icon/impl/gui/IconChooserPanel.java, open-sphere-base/mantle/src/main/java/io/opensphere/mantle/icon/impl/gui/IconManagerFrame.java, open-sphere-base/mantle/src/main/java/io/opensphere/mantle/icon/impl/gui/IconRotationDialog.java
Removed spinner arrows, changed JOption Messages, added bitmap/svg filters
=> GUI interface visual updates

open-sphere-base/core/.classpath, open-sphere-base/mantle/src/main/java/io/opensphere/mantle/infinity/InfinityQuerier.java, open-sphere-base/mantle/src/main/java/io/opensphere/mantle/infinity/InfinityUtilities.java, open-sphere-base/mantle/src/main/java/io/opensphere/mantle/infinity/QueryParameters.java, open-sphere-base/mantle/src/main/java/io/opensphere/mantle/infinity/QueryResults.java, open-sphere-plugins/infinity/src/main/java/io/opensphere/infinity/InfinityLayerController.java, open-sphere-plugins/infinity/src/main/java/io/opensphere/infinity/envoy/InfinityEnvoy.java, open-sphere-plugins/infinity/src/main/java/io/opensphere/infinity/json/Aggs.java, open-sphere-plugins/infinity/src/main/java/io/opensphere/infinity/json/Bins.java, open-sphere-plugins/infinity/src/main/java/io/opensphere/infinity/json/Bucket.java, open-sphere-plugins/infinity/src/main/java/io/opensphere/infinity/json/Histogram.java, open-sphere-plugins/infinity/src/test/java/io/opensphere/infinity/simulator/InfinitySimulator.java
Fixes #
-  Infinity Numeric binning working against simulator
-
-
-
=> Feature infinity binning

open-sphere-base/mantle/src/main/java/io/opensphere/mantle/infinity/InfinityUtilities.java, open-sphere-plugins/infinity/src/main/java/io/opensphere/infinity/envoy/InfinityEnvoy.java, open-sphere-plugins/infinity/src/main/java/io/opensphere/infinity/json/Histogram.java, open-sphere-plugins/infinity/src/test/java/io/opensphere/infinity/simulator/InfinitySimulator.java
Fixes #
-  Updates made during high-side testing
-  Removed 'Decimal Precision' and 'Show Empty Data Bin' controls.  These are not used in Infinity Mode
-
-
-
=> VORTEX-5733 Changes after high-side testing

open-sphere-base/core/src/main/java/io/opensphere/core/order/impl/DefaultOrderCategory.java, open-sphere-base/mantle/src/main/java/io/opensphere/mantle/crust/AbstractMantleController.java
Fixes #5862: Disabling exclusion areas
- General code clean up, addition of areas categories.
=> VORTEX-5862: Removing exclusion areas, updating code to behave properly.

open-sphere-base/core/.classpath, open-sphere-base/core/src/main/java/io/opensphere/core/util/fx/JFXAlertType.java
Fixes VORTEX-5847
- Break encapsulation on com.sun.javafx.scene.control.skin.resources
- Use ControlResources class to get the properties file
=> VORTEX-5847 Cannot delete Column Associations

open-sphere-base/core/.classpath, open-sphere-base/core/src/main/java/io/opensphere/core/util/fx/JFXAlertType.java
Reverts ngageoint/opensphere-desktop#203
Temporarily reverting to fix the build. This ticket will need to be done in a slightly different way.
=> Revert "VORTEX-5847 Cannot delete Column Associations"

.gitignore, open-sphere-base/core/src/main/java/io/opensphere/core/util/fx/JFXAlertType.java
=> Fix JFXAlertType

open-sphere-base/core/src/main/java/io/opensphere/core/quantify/QuantifyPlugin.java, open-sphere-base/core/src/main/java/io/opensphere/core/quantify/QuantifySender.java, open-sphere-base/core/src/main/java/io/opensphere/core/quantify/QuantifyService.java, open-sphere-base/core/src/main/java/io/opensphere/core/quantify/QuantifyToolbox.java, open-sphere-base/core/src/main/java/io/opensphere/core/quantify/QuantifyToolboxUtils.java, open-sphere-base/core/src/main/java/io/opensphere/core/quantify/impl/DefaultQuantifyService.java, open-sphere-base/core/src/main/java/io/opensphere/core/quantify/impl/HttpQuantifySender.java, open-sphere-base/core/src/main/java/io/opensphere/core/quantify/impl/LoggingQuantifySender.java, open-sphere-base/core/src/main/java/io/opensphere/core/quantify/impl/QuantifyToolboxImpl.java, open-sphere-base/core/src/main/java/io/opensphere/core/quantify/model/Metric.java, open-sphere-base/core/src/main/java/io/opensphere/core/quantify/model/package-info.java, open-sphere-base/core/src/main/java/io/opensphere/core/quantify/package-info.java, open-sphere-base/core/src/main/resources/pluginLoader.xml, open-sphere-plugins/wfs/src/main/resources/pluginLoader.xml
=> VORTEX-5865: Creating plugin to send metrics to a remote endpoint.

open-sphere-plugins/my-places/src/main/java/io/opensphere/myplaces/importer/MyPlacesCsvImporter.java, open-sphere-plugins/my-places/src/main/java/io/opensphere/tracktool/util/TrackUtils.java
Fixes VORTEX-5827
- Added method meant to deal with with importing My Places from CSVs so formatting isn't lost
=> VORTEX-5827 Track CSV import doesn't show bubbles or formatting

open-sphere-base/control-panels/pom.xml, open-sphere-base/mantle/src/main/java/io/opensphere/mantle/plugin/MantleMenuInit.java, open-sphere-maven-plugins/install-descriptor-maven-plugin/pom.xml, open-sphere-suite/pom.xml
=> Window in Icon Manager

open-sphere-base/mantle/src/main/java/io/opensphere/mantle/iconproject/model/PanelModel.java, open-sphere-base/mantle/src/main/java/io/opensphere/mantle/iconproject/model/ViewStyle.java, open-sphere-base/mantle/src/main/java/io/opensphere/mantle/iconproject/view/ButtonBuilder.java, open-sphere-base/mantle/src/main/java/io/opensphere/mantle/iconproject/view/IconProjNewView.java, open-sphere-base/mantle/src/main/java/io/opensphere/mantle/iconproject/view/MainPanel.java, open-sphere-base/mantle/src/main/java/io/opensphere/mantle/iconproject/view/TopMenuBar.java
=> there we go

open-sphere-base/mantle/src/main/java/io/opensphere/mantle/icon/impl/gui/IconBuilderDialog.java, open-sphere-base/mantle/src/main/java/io/opensphere/mantle/icon/impl/gui/IconBuilderPane.java, open-sphere-base/mantle/src/main/java/io/opensphere/mantle/iconproject/view/ButtonBuilder.java, open-sphere-base/mantle/src/main/java/io/opensphere/mantle/iconproject/view/IconProjBuilderDialog.java, open-sphere-base/mantle/src/main/java/io/opensphere/mantle/iconproject/view/IconProjDialog.java, open-sphere-base/mantle/src/main/java/io/opensphere/mantle/iconproject/view/IconProjFrame.java, open-sphere-base/mantle/src/main/java/io/opensphere/mantle/iconproject/view/IconProjNewView.java, open-sphere-base/mantle/src/main/java/io/opensphere/mantle/iconproject/view/IconProjPanel.java, open-sphere-base/mantle/src/main/java/io/opensphere/mantle/iconproject/view/MainPanel.java, open-sphere-base/mantle/src/main/java/io/opensphere/mantle/plugin/MantleMenuInit.java
=> Feature icon intern proj

eclipse/open-sphere-dictionary.txt, open-sphere-base/control-panels/src/main/java/io/opensphere/controlpanels/layers/activedata/ActiveDataPanel.java, open-sphere-base/control-panels/src/main/java/io/opensphere/controlpanels/layers/activedata/ActiveLayerControlPanel.java, open-sphere-base/control-panels/src/main/java/io/opensphere/controlpanels/layers/base/AbstractDiscoveryDataPanel.java, open-sphere-base/control-panels/src/main/java/io/opensphere/controlpanels/layers/layerdetail/LayerDetailLowerControlPanel.java, open-sphere-base/control-panels/src/main/java/io/opensphere/controlpanels/layers/layersets/LayerSetButtonPanel.java, open-sphere-base/core/src/main/java/io/opensphere/core/quantify/QuantifyToolboxUtils.java, open-sphere-base/mantle/src/main/java/io/opensphere/mantle/data/export/ExportMenuProvider.java, open-sphere-plugins/wfs/src/main/java/io/opensphere/wfs/gml311/GmlSaxFeatureResponseHandler.java
Fixes VORTEX-5878
- Instruments various parts of the code for metrics collection
- Adds utility methods for metrics collection
=> VORTEX-5878: Instrumenting analysis tools, layer manager

open-sphere-plugins/wps/src/main/java/io/opensphere/wps/LegacyWpsExecuteEnvoy.java, open-sphere-plugins/wps/src/main/java/io/opensphere/wps/WpsMantleController.java, open-sphere-suite/.classpath
Fixes VORTEX-5834
- Makes WPS more resilient
- Logs potential race condition for further analysis
=> Feature fix ogc connection

open-sphere-base/mantle/src/main/java/io/opensphere/mantle/icon/impl/gui/IconBuilderDialog.java, open-sphere-base/mantle/src/main/java/io/opensphere/mantle/icon/impl/gui/IconBuilderPane.java, open-sphere-base/mantle/src/main/java/io/opensphere/mantle/icon/impl/gui/IconChooserPanel.java, open-sphere-base/mantle/src/main/java/io/opensphere/mantle/icon/impl/gui/IconManagerFrame.java, open-sphere-base/mantle/src/main/java/io/opensphere/mantle/icon/impl/gui/IconTreeBuilder.java, open-sphere-base/mantle/src/main/java/io/opensphere/mantle/iconproject/impl/ButtonBuilder.java, open-sphere-base/mantle/src/main/java/io/opensphere/mantle/iconproject/impl/GridBuilder.java, open-sphere-base/mantle/src/main/java/io/opensphere/mantle/iconproject/impl/IconBuilderProjPane.java, open-sphere-base/mantle/src/main/java/io/opensphere/mantle/iconproject/impl/IconProjProps.java, open-sphere-base/mantle/src/main/java/io/opensphere/mantle/iconproject/impl/LabelMaker.java, open-sphere-base/mantle/src/main/java/io/opensphere/mantle/iconproject/impl/RecordImageIcon.java, open-sphere-base/mantle/src/main/java/io/opensphere/mantle/iconproject/model/PanelModel.java, open-sphere-base/mantle/src/main/java/io/opensphere/mantle/iconproject/view/IconProjBuilderNewDialog.java, open-sphere-base/mantle/src/main/java/io/opensphere/mantle/iconproject/view/IconProjDialog.java, open-sphere-base/mantle/src/main/java/io/opensphere/mantle/iconproject/view/MainPanel.java, open-sphere-base/mantle/src/main/java/io/opensphere/mantle/iconproject/view/TopMenuBar.java, open-sphere-base/mantle/src/main/java/io/opensphere/mantle/iconproject/view/TreeBuilder.java, open-sphere-base/mantle/src/main/java/io/opensphere/mantle/plugin/MantleMenuInit.java
=> Feature icon project kelly

open-sphere-base/mantle/src/main/java/io/opensphere/mantle/iconproject/impl/GridBuilder.java, open-sphere-base/mantle/src/main/java/io/opensphere/mantle/iconproject/impl/IconBuilderProjPane.java, open-sphere-base/mantle/src/main/java/io/opensphere/mantle/iconproject/impl/SpinnerBuilder.java, open-sphere-base/mantle/src/main/java/io/opensphere/mantle/iconproject/view/IconProjBuilderNewDialog.java, open-sphere-base/mantle/src/main/java/io/opensphere/mantle/iconproject/view/TopMenuBar.java, open-sphere-base/mantle/src/main/java/io/opensphere/mantle/plugin/MantleMenuInit.java
=> buildersizer

open-sphere-base/control-panels/src/main/java/io/opensphere/controlpanels/animation/config/v1/AnimationConfig.java, open-sphere-base/control-panels/src/main/java/io/opensphere/controlpanels/animation/controller/AnimationConfigManager.java, open-sphere-base/control-panels/src/main/java/io/opensphere/controlpanels/animation/controller/AnimationController.java, open-sphere-base/control-panels/src/main/java/io/opensphere/controlpanels/animation/model/AnimationModel.java, open-sphere-base/control-panels/src/main/java/io/opensphere/controlpanels/animation/view/ActiveWindowLayer.java, open-sphere-base/control-panels/src/main/java/io/opensphere/controlpanels/animation/view/AdvancedControlPanel.java, open-sphere-base/control-panels/src/main/java/io/opensphere/controlpanels/animation/view/AnimationDragHandlesLayer.java, open-sphere-base/control-panels/src/main/java/io/opensphere/controlpanels/animation/view/AnimationPanel.java, open-sphere-base/control-panels/src/main/java/io/opensphere/controlpanels/animation/view/ControlPanel.java, open-sphere-base/control-panels/src/main/java/io/opensphere/controlpanels/animation/view/HeldIntervalsLayer.java, open-sphere-base/control-panels/src/main/java/io/opensphere/controlpanels/animation/view/LoadIntervalsLayer.java, open-sphere-suite/.gitignore
Fixes #VORTEX-5882
- Adds metrics to the timeline functionality
-
-
=> VORTEX-5882 Instrumenting the timeline.

open-sphere-base/control-panels/src/main/java/io/opensphere/controlpanels/layers/availabledata/AvailableDataPanel.java, open-sphere-base/control-panels/src/main/java/io/opensphere/controlpanels/layers/base/AbstractDiscoveryDataLayerController.java, open-sphere-plugins/filter-builder/src/main/java/io/opensphere/filterbuilder2/manager/FilterManagerFilterPanel.java, open-sphere-plugins/filter-builder/src/main/java/io/opensphere/filterbuilder2/manager/FilterManagerPanel.java, open-sphere-plugins/ogc-server/src/main/java/io/opensphere/server/OGCServerPlugin.java, open-sphere-plugins/ogc-server/src/main/java/io/opensphere/server/manager/ServerManagerPanel.java
Fixes VORTEX-5884
- Add data collection metrics to add data, server manager, and filter manager panels
=> Instrument add data, server manager, and filter manager windows

open-sphere-base/mantle/src/main/java/io/opensphere/mantle/iconproject/impl/IconBuilderProjPane.java
=> Builder-Documentation

open-sphere-base/control-panels/src/main/java/io/opensphere/controlpanels/about/AboutPanel.java, open-sphere-base/control-panels/src/main/java/io/opensphere/controlpanels/animation/config/v1/AnimationConfig.java, open-sphere-base/control-panels/src/main/java/io/opensphere/controlpanels/animation/controller/AnimationConfigManager.java, open-sphere-base/control-panels/src/main/java/io/opensphere/controlpanels/animation/controller/AnimationController.java, open-sphere-base/control-panels/src/main/java/io/opensphere/controlpanels/animation/model/AnimationModel.java, open-sphere-base/control-panels/src/main/java/io/opensphere/controlpanels/animation/view/AdvancedControlPanel.java, open-sphere-base/control-panels/src/main/java/io/opensphere/controlpanels/animation/view/AnimationDragHandlesLayer.java, open-sphere-base/control-panels/src/main/java/io/opensphere/controlpanels/animation/view/ControlPanel.java, open-sphere-base/control-panels/src/main/java/io/opensphere/controlpanels/animation/view/HeldIntervalsLayer.java, open-sphere-base/control-panels/src/main/java/io/opensphere/controlpanels/animation/view/LoadIntervalsLayer.java, open-sphere-base/control-panels/src/main/java/io/opensphere/controlpanels/layers/activedata/ActiveDataPanel.java, open-sphere-base/control-panels/src/main/java/io/opensphere/controlpanels/layers/activedata/ActiveLayerControlPanel.java, open-sphere-base/control-panels/src/main/java/io/opensphere/controlpanels/layers/base/AbstractDiscoveryDataPanel.java, open-sphere-base/control-panels/src/main/java/io/opensphere/controlpanels/layers/layerdetail/LayerDetailLowerControlPanel.java, open-sphere-base/control-panels/src/main/java/io/opensphere/controlpanels/layers/layersets/LayerSetButtonPanel.java, open-sphere-base/control-panels/src/main/java/io/opensphere/controlpanels/state/StateView.java, open-sphere-base/core/src/main/java/io/opensphere/core/appl/DontShowDialogPlugin.java, open-sphere-base/core/src/main/java/io/opensphere/core/appl/Kernel.java, open-sphere-base/core/src/main/java/io/opensphere/core/appl/WhatsNewPlugin.java, open-sphere-base/core/src/main/java/io/opensphere/core/help/AboutDialog.java, open-sphere-base/core/src/main/java/io/opensphere/core/help/HelpManagerImpl.java, open-sphere-base/core/src/main/java/io/opensphere/core/quantify/Quantify.java, open-sphere-base/core/src/main/java/io/opensphere/core/quantify/QuantifyToolboxUtils.java, open-sphere-base/core/src/main/java/io/opensphere/core/quantify/QuantifyUtils.java, open-sphere-base/core/src/main/java/io/opensphere/core/quantify/impl/DefaultQuantifyService.java, open-sphere-base/mantle/src/main/java/io/opensphere/mantle/data/export/ExportMenuProvider.java, open-sphere-base/mantle/src/main/java/io/opensphere/mantle/plugin/selection/SelectionHandler.java, open-sphere-plugins/my-places/src/main/java/io/opensphere/tracktool/registry/TrackRegistry.java
=> VORTEX-5885: Instrumenting help, adding facade to simplify metrics collection

open-sphere-base/mantle/src/main/java/io/opensphere/mantle/icon/impl/gui/IconBuilderPane.java
Fixes #
-Add back in the up/down arrows for the icon builder.
-Sets tick speed to move faster in the builder.
-
=> add back sizing arrows

open-sphere-base/mantle/src/main/java/io/opensphere/mantle/icon/IconRecord.java, open-sphere-base/mantle/src/main/java/io/opensphere/mantle/iconproject/impl/IconBuilderProjPane.java, open-sphere-base/mantle/src/main/java/io/opensphere/mantle/iconproject/view/GridBuilder.java, open-sphere-base/mantle/src/main/java/io/opensphere/mantle/iconproject/view/IconProjDialog.java, open-sphere-base/mantle/src/main/java/io/opensphere/mantle/iconproject/view/MainPanel.java, open-sphere-base/mantle/src/main/java/io/opensphere/mantle/plugin/MantleMenuInit.java
=> Icon custom picking

open-sphere-base/mantle/src/main/java/io/opensphere/mantle/iconproject/impl/IconBuilderProjPane.java, open-sphere-base/mantle/src/main/java/io/opensphere/mantle/iconproject/model/IconMangerStyle.css
=> Icon Customizer display size fix

open-sphere-base/mantle/src/main/java/io/opensphere/mantle/icon/impl/gui/IconTreeBuilder.java, open-sphere-base/mantle/src/main/java/io/opensphere/mantle/iconproject/view/GridBuilder.java, open-sphere-base/mantle/src/main/java/io/opensphere/mantle/iconproject/view/IconProjDialog.java, open-sphere-base/mantle/src/main/java/io/opensphere/mantle/iconproject/view/MainPanel.java, open-sphere-base/mantle/src/main/java/io/opensphere/mantle/iconproject/view/TreeBuilder.java
=> Feature icon project gabby

open-sphere-base/mantle/src/main/java/io/opensphere/mantle/icon/impl/gui/IconBuilderDialog.java, open-sphere-base/mantle/src/main/java/io/opensphere/mantle/iconproject/impl/package-info.java, open-sphere-base/mantle/src/main/java/io/opensphere/mantle/iconproject/model/package-info.java, open-sphere-base/mantle/src/main/java/io/opensphere/mantle/iconproject/panels/GridBuilder.java, open-sphere-base/mantle/src/main/java/io/opensphere/mantle/iconproject/panels/IconBuilderProjPane.java, open-sphere-base/mantle/src/main/java/io/opensphere/mantle/iconproject/panels/package-info.java, open-sphere-base/mantle/src/main/java/io/opensphere/mantle/iconproject/view/IconProjBuilderNewDialog.java, open-sphere-base/mantle/src/main/java/io/opensphere/mantle/iconproject/view/IconProjDialog.java, open-sphere-base/mantle/src/main/java/io/opensphere/mantle/iconproject/view/IconProjNewView.java, open-sphere-base/mantle/src/main/java/io/opensphere/mantle/iconproject/view/package-info.java, open-sphere-base/mantle/src/main/resources/IconMangerStyle.css
=> Documentation and Cust save fix

open-sphere-base/core/src/main/java/io/opensphere/core/modulestate/StateUtilities.java, open-sphere-plugins/feature-actions/src/main/java/io/opensphere/featureactions/FeatureActionsPlugin.java, open-sphere-plugins/feature-actions/src/main/java/io/opensphere/featureactions/controller/FeatureActionStateConstants.java, open-sphere-plugins/feature-actions/src/main/java/io/opensphere/featureactions/controller/FeatureActionStateController.java
Fixes VORTEX-5890
- Add a controller for importing/exporting feature actions via states
- Added support for controller in FeatureActionsPlugin and StateUtilities
=> VORTEX-5890 Import/Export Feature Actions

open-sphere-base/mantle/src/main/java/io/opensphere/mantle/iconproject/impl/DefaultIconRecordTreeItemObject.java, open-sphere-base/mantle/src/main/java/io/opensphere/mantle/iconproject/panels/GridBuilder.java, open-sphere-base/mantle/src/main/java/io/opensphere/mantle/iconproject/panels/MainPanel.java, open-sphere-base/mantle/src/main/java/io/opensphere/mantle/plugin/MantleMenuInit.java
=> icon updates

open-sphere-base/mantle/src/main/java/io/opensphere/mantle/iconproject/impl/DefaultIconRecordTreeItemObject.java, open-sphere-base/mantle/src/main/java/io/opensphere/mantle/iconproject/panels/GridBuilder.java, open-sphere-base/mantle/src/main/java/io/opensphere/mantle/iconproject/panels/MainPanel.java, open-sphere-base/mantle/src/main/java/io/opensphere/mantle/iconproject/panels/SubCollectPane.java, open-sphere-base/mantle/src/main/java/io/opensphere/mantle/iconproject/panels/TreeBuilder.java
=> empty category improvements

open-sphere-base/mantle/src/main/java/io/opensphere/mantle/iconproject/model/PanelModel.java, open-sphere-base/mantle/src/main/java/io/opensphere/mantle/iconproject/panels/CollectNamesPane.java, open-sphere-base/mantle/src/main/java/io/opensphere/mantle/iconproject/panels/MainPanel.java, open-sphere-base/mantle/src/main/java/io/opensphere/mantle/iconproject/panels/TopMenuBar.java, open-sphere-base/mantle/src/main/java/io/opensphere/mantle/iconproject/view/AddIconDialog.java, open-sphere-base/mantle/src/main/java/io/opensphere/mantle/iconproject/view/IconCustomizerDialog.java, open-sphere-base/mantle/src/main/java/io/opensphere/mantle/iconproject/view/IconProjDialog.java
=> Feature icon project

open-sphere-plugins/arcgis/src/main/java/io/opensphere/arcgis2/esri/EsriPictureFillSymbol.java, open-sphere-plugins/arcgis/src/main/java/io/opensphere/arcgis2/esri/EsriSimpleFillSymbol.java, open-sphere-plugins/arcgis/src/main/java/io/opensphere/arcgis2/esri/EsriSimpleLineSymbol.java, open-sphere-plugins/arcgis/src/main/java/io/opensphere/arcgis2/esri/EsriUniqueValueRenderer.java
Removed default serialVersionUID from classes causing server connection issues.
=> VORTEX-5915 Unable to connect to server - class incompatibility

open-sphere-plugins/arcgis/src/main/java/io/opensphere/arcgis2/envoy/ArcGISLayerListEnvoy.java
Fixes querying services for ArcGIS servers.
=> VORTEX-5915 ArcGIS Connection Issues

open-sphere-base/core/src/main/java/io/opensphere/core/util/ColorUtilities.java, open-sphere-base/core/src/test/java/io/opensphere/core/util/ColorUtilitiesTest.java
Needed a lighter color for showing that a histogram bar was selected so added a method to generate a lighter color to ColorUtilities. Wrote a test to make sure that the saturation of the lighter color is coming out to roughly half even after a color is lightened a few times.
=> VORTEX-5908 Histogram - implement new menu options

open-sphere-plugins/kml/src/main/java/io/opensphere/kml/mantle/controller/KMLGeometryBuilder.java
Fixes #5929
- Fix issue on import of KML with polygon that overlaps itself
=> VORTEX-5929 Fixing issue with KML import causing ignore of bad polygons

open-sphere-base/mantle/src/main/java/io/opensphere/mantle/infinity/InfinityQuerier.java, open-sphere-plugins/kml/src/main/java/io/opensphere/kml/envoy/KMLDataLoader.java
Fixing NPE with Infinity null bin parameters & issue with spaces in file paths for KML files.
=> Quick fixes for 5.2.4 (Infinity and KML)

open-sphere-base/control-panels/src/main/java/io/opensphere/controlpanels/animation/TimelinePlugin.java, open-sphere-base/control-panels/src/main/java/io/opensphere/controlpanels/layers/LayersFrame.java, open-sphere-base/control-panels/src/main/java/io/opensphere/controlpanels/layers/util/FeatureTypeLabel.java, open-sphere-base/control-panels/src/main/java/io/opensphere/controlpanels/recording/VideoRecorderPlugin.java, open-sphere-base/core/src/main/java/io/opensphere/core/dialog/alertviewer/AlertViewerController.java, open-sphere-base/overlay/src/main/java/io/opensphere/overlay/GlobeBackgroundManager.java, open-sphere-base/overlay/src/main/java/io/opensphere/overlay/arc/ArcTransformer.java, open-sphere-base/overlay/src/main/java/io/opensphere/overlay/query/QuerySelector.java
Fixes VORTEX-5921
- Consistency changes/spelling fixes for many existing Icon Legend entries
- Added Icon Legend entries for buttons that did not have them
=> VORTEX-5921 Icon Legend out of date

open-sphere-base/control-panels/src/main/java/io/opensphere/controlpanels/layers/LayersFrame.java
Fixes VORTEX-5936
- Changed style of layers panel tabs so they are more visible
=> VORTEX-5936 Make Tabs in Layers Panel Obviously Selected

open-sphere-base/core/src/main/java/io/opensphere/core/util/jts/core/JTSCoreGeometryUtilities.java
Fixes #5961
- Add utilities to support multipolygons
=> VORTEX-5961: Creating utilities to handle multipolygons.

open-sphere-base/overlay/src/main/java/io/opensphere/overlay/query/QuerySelector.java
Fixes #5963
- Clicking the button when toggled will now untoggle it.
- Pressing escape when toggled will now untoggle it
- Pressing clear and accepting the dialog will now untoggle it.
=> VORTEX-5963: Fixing query button behavior to toggle off in multiple situations

open-sphere-base/mantle/src/main/java/io/opensphere/mantle/data/impl/DataGroupInfoGroupByUtility.java
Fixes VORTEX-5959
- Areas no longer show up in the add data window
=> VORTEX-5959 Area item in Add Data window

open-sphere-base/core/src/main/java/io/opensphere/core/geometry/MultiPolygonGeometry.java, open-sphere-base/core/src/main/java/io/opensphere/core/util/jts/core/JTSCoreGeometryUtilities.java, open-sphere-base/mantle/src/main/java/io/opensphere/mantle/plugin/queryregion/impl/QueryRegionManagerImpl.java, open-sphere-base/mantle/src/main/java/io/opensphere/mantle/plugin/selection/BufferRegionCreator.java, open-sphere-base/mantle/src/main/java/io/opensphere/mantle/plugin/selection/SelectionHandler.java
Fixes #5961
- Adds multipolygon behavior to all commands. 
-
-
=> Applying multi-polygon actions to all commands.

open-sphere-base/control-panels/src/main/java/io/opensphere/controlpanels/layers/activedata/controller/ActiveDataDataLayerController.java, open-sphere-base/control-panels/src/main/java/io/opensphere/controlpanels/layers/base/AbstractDiscoveryDataLayerController.java, open-sphere-base/control-panels/src/main/java/io/opensphere/controlpanels/layers/base/AbstractDiscoveryDataPanel.java, open-sphere-base/control-panels/src/main/java/io/opensphere/controlpanels/layers/base/LayerUtilities.java, open-sphere-base/mantle/src/main/java/io/opensphere/mantle/data/impl/DefaultDataGroupInfo.java, open-sphere-plugins/my-places/src/main/java/io/opensphere/myplaces/controllers/DataGroupInfoMemberRemovedListener.java
Fixes #5975
- Fixes the delete mechanism to work in z-order mode (previously deleting my places in z-order mode wouldn't work)
=> VORTEX-5975: Fixing delete mechanism to work properly in z-order mode.

open-sphere-base/mantle/src/main/java/io/opensphere/mantle/util/JTSGMLUtilities.java
=> Feature query areas with holes

open-sphere-base/control-panels/src/main/java/io/opensphere/controlpanels/viewbookmark/controller/ViewBookmarkMenuItemProvider.java, open-sphere-base/core/src/main/java/io/opensphere/core/map/MapManagerMenuProvider.java, open-sphere-plugins/my-places/src/main/java/io/opensphere/myplaces/controllers/SingleGroupContextMenuProvider.java, open-sphere-plugins/my-places/src/main/java/io/opensphere/myplaces/specific/MyPointsMenuItemProvider.java, open-sphere-plugins/my-places/src/main/java/io/opensphere/myplaces/specific/points/PointGeometryContextMenuProvider.java, open-sphere-plugins/my-places/src/main/java/io/opensphere/myplaces/specific/regions/RegionTypeController.java
Fixes #5978
- Fix generation of right click menus so that the correct options are displayed
- Add icons to those missing them
- Correct language to be more consistent.
=> VORTEX-5978: Fixing right click on map option to properly create places.

open-sphere-plugins/my-places/src/main/java/io/opensphere/myplaces/specific/regions/RegionTypeController.java
Fixes VORTEX-5973
- added methods for creating places from areas from the layers menu
=> VORTEX-5973 Save to places on area doesn't work from layer manager

open-sphere-base/core/src/main/java/io/opensphere/core/geometry/MultiPolygonGeometry.java
Fixes
- Geometry mutator is non-public
=> Fix GeometryTest Failure

open-sphere-base/control-panels/src/main/java/io/opensphere/controlpanels/animation/view/ActiveWindowLayer.java, open-sphere-base/core/src/main/java/io/opensphere/core/control/action/MenuOption.java, open-sphere-base/core/src/main/java/io/opensphere/core/map/MapManagerMenuProvider.java, open-sphere-base/mantle/src/main/java/io/opensphere/mantle/plugin/queryline/impl/QueryLineManagerImpl.java, open-sphere-base/mantle/src/main/java/io/opensphere/mantle/plugin/queryregion/QueryRegionManager.java, open-sphere-base/mantle/src/main/java/io/opensphere/mantle/plugin/queryregion/impl/QueryRegionManagerImpl.java, open-sphere-base/mantle/src/main/java/io/opensphere/mantle/plugin/selection/SelectionCommandFactory.java, open-sphere-base/mantle/src/main/java/io/opensphere/mantle/plugin/selection/SelectionHandler.java, open-sphere-base/mantle/src/main/java/io/opensphere/mantle/plugin/selection/impl/AbstractSelectionCommand.java, open-sphere-base/mantle/src/main/java/io/opensphere/mantle/plugin/selection/impl/CenterOnCommand.java, open-sphere-base/mantle/src/main/java/io/opensphere/mantle/plugin/selection/impl/ZoomToCommand.java, open-sphere-base/mantle/src/main/java/io/opensphere/mantle/toolbox/MantleToolboxImpl.java, open-sphere-base/overlay/src/main/java/io/opensphere/overlay/SelectionRegionControls.java, open-sphere-base/overlay/src/main/java/io/opensphere/overlay/SelectionRegionMenuProvider.java, open-sphere-plugins/filter-builder/src/main/java/io/opensphere/filterbuilder/GeometryContextMenuProvider.java, open-sphere-plugins/heatmap/src/main/java/io/opensphere/heatmap/HeatmapGeometryMenuProvider.java, open-sphere-plugins/heatmap/src/main/java/io/opensphere/heatmap/HeatmapLayerMenuProvider.java, open-sphere-plugins/my-places/src/main/java/io/opensphere/myplaces/controllers/SingleGroupContextMenuProvider.java, open-sphere-plugins/my-places/src/main/java/io/opensphere/myplaces/specific/MyPointsMenuItemProvider.java, open-sphere-plugins/my-places/src/main/java/io/opensphere/myplaces/specific/points/PointGeometryContextMenuProvider.java, open-sphere-plugins/my-places/src/main/java/io/opensphere/myplaces/specific/regions/RegionTypeController.java, open-sphere-plugins/my-places/src/main/java/io/opensphere/myplaces/specific/regions/utils/RegionUtils.java
Fixes VORTEX-5989
- Reorder load and add menus to match web tool
- Update spacing between menu items to match web tool
- Update group text headings to match web tool
- Update text and icons on some menu items to match web tool
=> Feature reverse query menus

open-sphere-base/mantle/src/main/java/io/opensphere/mantle/icon/impl/gui/IconBuilderPane.java, open-sphere-base/mantle/src/main/java/io/opensphere/mantle/iconproject/impl/TreePopupMenuImpl.java, open-sphere-base/mantle/src/main/java/io/opensphere/mantle/iconproject/model/PanelModel.java, open-sphere-base/mantle/src/main/java/io/opensphere/mantle/iconproject/panels/GridBuilder.java, open-sphere-base/mantle/src/main/java/io/opensphere/mantle/iconproject/panels/IconCustomizerPane.java, open-sphere-base/mantle/src/main/java/io/opensphere/mantle/iconproject/panels/MainPanel.java, open-sphere-base/mantle/src/main/java/io/opensphere/mantle/iconproject/panels/TopMenuBar.java
Fixes
- Implements filter bar to match entered text to the names of the icon in the panel listing
- misc. icon manager adjustments: size of buttons, extraneous variables, renaming methods
=> Icon Manager Filter Bar

open-sphere-base/core/.classpath, pom.xml
Fixes VORTEX-5713
- Update dependencies 
-
-
=> Feature dependency upgrade

open-sphere-base/mantle/src/main/java/io/opensphere/mantle/plugin/selection/SelectionCommandFactory.java, open-sphere-base/mantle/src/main/java/io/opensphere/mantle/plugin/selection/impl/CancelQueryCommand.java
Fixes
- cancel query menu option shows up, also it has an icon
=> Cancel Query

open-sphere-base/core/src/main/java/io/opensphere/core/pipeline/processor/LabelProcessor.java, open-sphere-base/mantle/src/main/java/io/opensphere/mantle/data/geom/style/impl/AbstractFeatureVisualizationStyle.java
Fixes #VORTEX-5986
- Feature offset label on hover
-
-
=> Feature offset label on hover

open-sphere-base/control-panels/src/main/java/io/opensphere/controlpanels/layers/activedata/LayerControlPanel.java, open-sphere-base/mantle/src/main/java/io/opensphere/mantle/data/impl/DefaultTileLevelController.java, open-sphere-base/xyz-tile/src/main/java/io/opensphere/xyztile/mantle/XYZMantleController.java
Fixes
- Hold Level spinner for layers works
=> Hold Level

open-sphere-base/analysis/src/main/java/io/opensphere/analysis/util/MGRSUtilities.java
Fixes #VORTEX-6002
- Propagate changes from visualization state for MGRS wrapped data element.
=> Feature fix visualization state

open-sphere-base/analysis/src/main/java/io/opensphere/analysis/baseball/BaseballController.java
Fixes
- Baseball Card now grabs nearby points from other layers
=> Multiple Layers Baseball Card

open-sphere-base/core/src/main/java/io/opensphere/core/appl/Kernel.java, open-sphere-base/core/src/main/java/io/opensphere/core/dialog/LoggerDialog.java
Fixes #
- User modified logger settings persist across sessions
=> Logger Settings Session Persistance

Jenkinsfile, open-sphere-base/analysis/src/test/java/io/opensphere/analysis/listtool/model/ListToolTableModelTest.java, open-sphere-base/control-panels/src/test/java/io/opensphere/controlpanels/styles/model/StyleOptionsTest.java, open-sphere-base/core/src/test/java/io/opensphere/core/math/MagneticHeadingCalculatorTest.java, open-sphere-base/core/src/test/java/io/opensphere/core/util/concurrent/ProcrastinatingExecutorTest.java, open-sphere-plugins/csv-common/src/main/java/io/opensphere/csvcommon/detect/location/algorithm/decider/SingleLocationColumnDecider.java, open-sphere-plugins/csv-common/src/test/java/io/opensphere/csvcommon/detect/controller/DetectionControllerImplTest.java, open-sphere-plugins/csv-common/src/test/java/io/opensphere/csvcommon/ui/columndefinition/controller/TypeControllerTest.java, open-sphere-plugins/geopackage/src/main/java/io/opensphere/geopackage/util/GeoPackageCoordinateUtils.java, open-sphere-plugins/geopackage/src/test/java/io/opensphere/geopackage/importer/tile/TileRowImporterImplTest.java, open-sphere-plugins/ogc-server/src/test/java/io/opensphere/server/serverprovider/http/factory/HttpServerFactoryTest.java, open-sphere-plugins/ogc-server/src/test/java/io/opensphere/server/serverprovider/http/requestors/FilePostRequestorTest.java, open-sphere-plugins/ogc-server/src/test/java/io/opensphere/server/serverprovider/http/requestors/GetRequestorTest.java, open-sphere-plugins/ogc-server/src/test/java/io/opensphere/server/serverprovider/http/requestors/PostRequestorImplTest.java
Fixes failing JUnit tests
-
-
-
=> Feature junit fix

open-sphere-base/mantle/src/main/java/io/opensphere/mantle/data/dynmeta/impl/DynamicMetadataDataTypeControllerImpl.java
Fixes
- Dynamic columns are added at a column index one higher
=> Dynamic Column Missing data

open-sphere-base/mantle/src/main/java/io/opensphere/mantle/data/geom/style/dialog/MiniStylePanel.java, open-sphere-base/mantle/src/main/java/io/opensphere/mantle/data/geom/style/dialog/MiniStyleTypePanel.java, open-sphere-base/mantle/src/main/java/io/opensphere/mantle/data/geom/style/dialog/MiniStyleTypePanelController.java
Fixes #6077
- Fix layout of mini style panel to avoid horizontal scrolling
=> VORTEX-6077: Fixing layout of mini style panel.

open-sphere-base/overlay/src/main/java/io/opensphere/overlay/CursorPositionPopupManager.java, open-sphere-base/overlay/src/main/java/io/opensphere/overlay/CursorPositionTransformer.java
Fixes #6071
- Adds DD, DMS, DDM and MGRS, plus altitude to the dot popup.
=> VORTEX-6071: Adding all coordinate formats to the dot popup

open-sphere-plugins/wfs/src/main/java/io/opensphere/wfs/envoy/WFSEnvoyHelper.java
=> Requery after using count-by doesnt work

open-sphere-base/analysis/src/main/java/io/opensphere/analysis/baseball/BaseballDataRow.java, open-sphere-base/analysis/src/main/java/io/opensphere/analysis/baseball/BaseballPanel.java
Fixes VORTEX-6114
- Data can now be reordered under the "Field" and "Value" headings
- Data can be copied to clipboard by double clicking a data cell
=> VORTEX-6114 Unable to order by column in new baseball card.

open-sphere-base/core/src/main/java/io/opensphere/core/util/fx/AutoSelectComboBox.java
Fixes #6134
- Fixing typeahead issues in auto-select combo-box
=> VORTEX-6134: Fixing typeahead issues in auto-select combo-box

open-sphere-base/analysis/src/main/java/io/opensphere/analysis/baseball/BaseballDataRow.java, open-sphere-base/analysis/src/main/java/io/opensphere/analysis/baseball/BaseballElementRow.java, open-sphere-base/analysis/src/main/java/io/opensphere/analysis/baseball/BaseballPanel.java
=> Text nodes instead of just strings. Clickable URL support.

open-sphere-plugins/arcgis/src/main/java/io/opensphere/arcgis2/ArcGIS2Plugin.java, open-sphere-plugins/arcgis/src/main/java/io/opensphere/arcgis2/ArcGISContextMenuProvider.java, open-sphere-plugins/arcgis/src/main/java/io/opensphere/arcgis2/envoy/ArcRestEnvoy.java, open-sphere-plugins/arcgis/src/main/java/io/opensphere/arcgis2/envoy/ArcRestEnvoyUtils.java, open-sphere-plugins/arcgis/src/main/java/io/opensphere/arcgis2/mantle/ArcGISDataElementHelper.java, open-sphere-plugins/arcgis/src/main/java/io/opensphere/arcgis2/mantle/ArcGISLayerInfoProvider.java, open-sphere-plugins/arcgis/src/main/java/io/opensphere/arcgis2/mantle/ArcGISLayerProvider.java
Fixes #6095
- Enable time support in ArcGIS layers
- Add parsing to read time for features in ArcGIS layers
- Correct issues preventing use of complex polygons for query areas on ArcGIS layers.
=> Feature arclayer times

open-sphere-base/mantle/src/main/java/io/opensphere/mantle/icon/chooser/view/IconDetail.java, open-sphere-base/mantle/src/main/java/io/opensphere/mantle/icon/impl/IconRegistryImpl.java
Fixes VORTEX-6039
- Add rotated/scaled/positioned icons to `User Added` collection
- Add default pin icon only if it doesn't exist (instead of adding it and then removing??)
=> VORTEX-6038

open-sphere-install/open-sphere-install-windows64/.project, open-sphere-plugins/search/src/main/java/io/opensphere/search/controller/SearchExecutor.java
=> Feature build

open-sphere-base/mantle/src/main/java/io/opensphere/mantle/icon/chooser/model/IconChooserModel.java, open-sphere-base/mantle/src/main/java/io/opensphere/mantle/icon/chooser/view/IconDetail.java, open-sphere-base/mantle/src/main/java/io/opensphere/mantle/icon/chooser/view/IconSelectionPanel.java
Fixes VORTEX-6116 (268), 289, 
- Enable editing of icon name for custom icon modifications
- Enable editing of icon collection/source
- Revert a previous change -- Icons are not automatically added to "User Added" collection because you can now select the source
- Fully implements new icon tabs
=> Icon Customization

open-sphere-base/control-panels/src/main/java/io/opensphere/controlpanels/animation/config/v1/AnimationConfig.java
Fixes VORTEX-6080
- Timeline loop duration default = a day.
=> VORTEX-6080

open-sphere-plugins/wfs/src/main/java/io/opensphere/wfs/envoy/WFSEnvoy.java
Fixes #
Fix for eclipse hanging and stops printing wfs response to standard out.
-
-
-
=> Fix for outputing response to system.out.

open-sphere-plugins/filter-builder/src/main/java/io/opensphere/filterbuilder2/manager/FilterManagerFilterPanel.java
Fixes VORTEX-6032
- Static icons for `FilterManagerFilterPanel` that get reused for buttons.
=> VORTEX-6032

open-sphere-plugins/filter-builder/src/main/java/io/opensphere/filterbuilder2/editor/advanced/FilterTreeCellPanel.java, open-sphere-plugins/filter-builder/src/main/java/io/opensphere/filterbuilder2/manager/FilterManagerFilterPanel.java
Additional icon updates. Fixes the colors.
=> VORTEX-6032-2

open-sphere-base/mantle/src/main/java/io/opensphere/mantle/data/impl/DefaultDataGroupInfo.java
Add time extents to `Add Data` menu layer descriptions.
=> VORTEX-6088

open-sphere-base/analysis/src/main/java/io/opensphere/analysis/baseball/BaseballPanel.java
Fixes VORTEX-6142
- Layer name of currently selected feature added to top of the panel
- Coordinate label and buttons now on one line
- Coordinate buttons are labels that indicate selection status using borders
- Fixed bug causing error when clicking the data column headings
- Mouse cursor only changes when first hovering over a URL
=> VORTEX-6142: Baseball card feature layer info

open-sphere-base/mantle/src/main/java/io/opensphere/mantle/controller/impl/DataGroupActivationController.java
Fixes VORTEX-6128 (maybe), VORTEX-6139.
=> Fix DataSource Deactivation

open-sphere-base/control-panels/src/main/java/io/opensphere/controlpanels/layers/LayersFrame.java, open-sphere-base/control-panels/src/main/java/io/opensphere/controlpanels/layers/event/TabChangeListener.java, open-sphere-base/control-panels/src/main/java/io/opensphere/controlpanels/layers/layerdetail/LayerDetailPanel.java
=> Layer Details Tabs

open-sphere-base/core/src/main/java/io/opensphere/core/cache/util/IntervalPropertyValueSet.java
Fixes #6132
- Fixes issue with envelope creation (should be a geometry with the same coordinates as the envelope)
=> Feature query polygons

open-sphere-plugins/heatmap/src/main/java/io/opensphere/heatmap/HeatmapGeometryUtilities.java
=> VORTEX-5988 Heatmap LOB Display

open-sphere-plugins/feature-actions/src/main/java/io/opensphere/featureactions/controller/FeatureActionStateController.java, open-sphere-plugins/wfs/src/main/java/io/opensphere/wfs/state/activate/WFSStateActivator.java, open-sphere-plugins/wfs/src/main/java/io/opensphere/wfs/state/deactivate/WFSStateDeactivator.java, open-sphere-plugins/wms/src/main/java/io/opensphere/wms/state/BaseWmsStateController.java, open-sphere-plugins/wms/src/main/java/io/opensphere/wms/state/activate/StateActivator.java, open-sphere-plugins/wms/src/main/java/io/opensphere/wms/state/deactivate/StateDeactivator.java, open-sphere-plugins/wms/src/test/java/io/opensphere/wms/state/deactivate/StateDeactivatorTest.java
Fixes VORTEX-6066
- activation/deactivation of states with data and map layers now toggles the original layer on/off instead of creating new layers
=> VORTEX-6066 State load duplicates layers

open-sphere-base/control-panels/src/main/java/io/opensphere/controlpanels/layers/availabledata/AvailableDataTreeTableTreeCellRenderer.java, open-sphere-base/control-panels/src/main/java/io/opensphere/controlpanels/layers/util/ClockAndOrColorLabel.java
Fixes #367 
- Updates the logic used for color selection
- Corrects issue with picking the correct icon for time-based layers. 
-
-
=> VORTEX-6075: Updating color logic for icons.

open-sphere-base/mantle/src/main/java/io/opensphere/mantle/icon/impl/CompressedCollectionIconSource.java
=> Fix importing icons from archive files

open-sphere-base/core/src/main/java/io/opensphere/core/hud/framework/Frame.java, open-sphere-base/core/src/main/java/io/opensphere/core/hud/framework/Window3D.java, open-sphere-base/core/src/main/java/io/opensphere/core/map/MapManagerImpl.java, open-sphere-base/core/src/main/java/io/opensphere/core/pipeline/NoScale.java, open-sphere-base/core/src/main/java/io/opensphere/core/pipeline/PipelineCanvasHelper.java, open-sphere-base/core/src/main/java/io/opensphere/core/pipeline/PipelineGLCanvas.java, open-sphere-base/core/src/main/java/io/opensphere/core/pipeline/PipelineImpl.java, open-sphere-base/core/src/main/java/io/opensphere/core/pipeline/ScaleDetector.java, open-sphere-base/core/src/main/java/io/opensphere/core/pipeline/processor/RenderToTextureProcessorHelper.java, open-sphere-base/core/src/main/java/io/opensphere/core/viewer/impl/AbstractDynamicViewer.java, open-sphere-base/core/src/main/java/io/opensphere/core/viewer/impl/AbstractViewer.java, open-sphere-base/core/src/main/java/io/opensphere/core/viewer/impl/ScreenViewer.java, open-sphere-base/core/src/main/java/io/opensphere/core/viewer/impl/Viewer2D.java, open-sphere-base/core/src/main/java/io/opensphere/core/viewer/impl/Viewer3D.java, open-sphere-base/core/src/main/java/io/opensphere/core/viewer/impl/ViewerManager.java, open-sphere-base/core/src/test/java/io/opensphere/core/viewer/impl/Viewer2DTest.java, open-sphere-base/core/src/test/java/io/opensphere/core/viewer/impl/Viewer3DTest.java, open-sphere-base/overlay/src/main/java/io/opensphere/overlay/compass/HUDCompass.java, open-sphere-plugins/hud/src/main/java/io/opensphere/hud/glswing/GLSwingAWTEventListener.java, open-sphere-plugins/hud/src/main/java/io/opensphere/hud/util/Frame3D.java
Fixes #
Globe rendering issues on high dpi monitors with grandpa mode enabled.
-
-
-
=> Ft highdpi

open-sphere-base/core/src/main/java/io/opensphere/core/quantify/QuantifyPlugin.java, open-sphere-base/core/src/main/java/io/opensphere/core/quantify/impl/DefaultQuantifyService.java, open-sphere-base/core/src/main/java/io/opensphere/core/quantify/impl/LoggingQuantifySender.java, open-sphere-base/mantle/src/main/java/io/opensphere/mantle/data/geom/style/impl/ui/LabelComboEditor.java, open-sphere-plugins/arcgis/src/main/java/io/opensphere/arcgis2/mantle/ArcGISMantleController.java, open-sphere-plugins/feature-actions/src/main/java/io/opensphere/featureactions/editor/model/FeatureActionImporter.java
=> Feature crash fixes

open-sphere-base/analysis/src/main/java/io/opensphere/analysis/baseball/BaseballPanel.java
Fixes #6104
- Update linker to use keys instead of values for link detection
- Change default color to yellow
=> VORTEX-6104: Updating linking to use keys instead of values.

open-sphere-base/analysis/src/main/java/io/opensphere/analysis/baseball/BaseballDataRow.java, open-sphere-base/analysis/src/main/java/io/opensphere/analysis/baseball/BaseballPanel.java
Fixes
- Adds support for displaying images in the baseball card, image is scaled based on the width of the value column
- Swapping the position of columns is now disabled
=> Baseball Images

open-sphere-base/core/src/main/java/io/opensphere/core/pipeline/processor/PolygonProcessor.java, open-sphere-plugins/kml/src/main/java/io/opensphere/kml/envoy/KMLParserPool.java
Fixes #6106
- Fixes some really strange KML behavior to account for bad polygon structures.
=> VORTEX-6106: Improving KML Support

open-sphere-base/control-panels/src/main/java/io/opensphere/controlpanels/layers/base/AbstractDiscoveryDataPanel.java, open-sphere-base/core/src/main/java/io/opensphere/core/cache/jdbc/InsertTask.java
Fixes
- setValue uses LOGGER instead of having an uncaught error, error message includes DataModelCategory if applicable
- getRootNode returns null is the tree or model is null
=> Logging Correction

open-sphere-base/mantle/src/main/java/io/opensphere/mantle/plugin/queryregion/impl/QueryRegionManagerImpl.java
Fixes VORTEX-6233
- query regions duplicate to the new query region are removed so features aren't loaded several times
=> VORTEX-6233 Add Data button misbehaving

open-sphere-base/analysis/src/main/java/io/opensphere/analysis/util/MGRSUtilities.java, open-sphere-base/mantle/src/main/java/io/opensphere/mantle/data/MetaDataInfo.java, open-sphere-base/mantle/src/main/java/io/opensphere/mantle/data/impl/DefaultMetaDataInfo.java, open-sphere-plugins/wfs/src/main/java/io/opensphere/wfs/envoy/WFSEnvoyHelper.java
Fixes VORTEX-6235
- A list of user added columns is kept in the metadata
- User added column are removed before a query
=> VORTEX-6235 User added columns prevent retrieval of features

open-sphere-base/mantle/src/main/java/io/opensphere/mantle/data/cache/impl/DynamicMetaDataListCodeGenerator.java
Fixes VORTEX-6218
- add more thorough handling of date formats to the set function on metadata code generator
=> VORTEX-6218 Time doesn't display in Baseball Feature Info

open-sphere-base/core/src/main/java/io/opensphere/core/util/javafx/input/IntegerSpinnerInputValidator.java
Fixes VORTEX-6223
- add input validator for integer spinner so bad user input is properly managed
=> VORTEX-6223 Creating buffer reads decimal distance wrong

open-sphere-base/core/src/main/java/io/opensphere/core/control/keybinding/ControlUI.java, open-sphere-base/core/src/main/java/io/opensphere/core/control/keybinding/MenuShortCut.java, open-sphere-base/core/src/main/java/io/opensphere/core/control/keybinding/MenuShortCutsUI.java
Fixes # Slight refactor to KeyMap
- remove re-used string to make static final strings. 
- update comments.
=> Ft key patch

pom.xml
Fixes # Remove Duplicate Dependencies
-
-
-
=> remove duplicate dependencies

pom.xml
Fixes # possible security issue.
- update from 8.9 --> 8.18
-
-
=> update puppycrawl for security

open-sphere-base/core/src/main/java/io/opensphere/core/util/swing/tags/JTag.java, open-sphere-base/core/src/main/java/io/opensphere/core/util/swing/tags/JTagField.java
Fixes VORTEX-6190
- added handling of specific color for the text of the classification tags
- classification tag text isn't disabled
=> VORTEX-6190 Duty Org Color Update

open-sphere-base/core/src/test/java/io/opensphere/core/units/angle/AngleUnitsProviderTest.java
Fixes #
Update Test to Reflect changes
-
-
-
=> Fix Unit Test for Angle Unit Providers

open-sphere-plugins/wps/src/test/java/io/opensphere/wps/streaming/impl/StreamSubscriberTest.java
Fixes #
Update Streaming Unit Test
-
-
-
=> VORTEX: 6265

open-sphere-base/core/src/main/java/io/opensphere/core/viewbookmark/util/ViewBookmarkUtil.java, open-sphere-base/core/src/main/java/io/opensphere/core/viewer/impl/ViewerAnimator.java, open-sphere-base/mantle/src/main/java/io/opensphere/mantle/data/util/impl/DataElementActionUtilsImpl.java, open-sphere-base/mantle/src/main/java/io/opensphere/mantle/data/util/impl/DataTypeActionUtils.java, open-sphere-plugins/filter-builder/src/main/java/io/opensphere/filterbuilder/GeometryContextMenuProvider.java, open-sphere-plugins/filter-builder/src/main/java/io/opensphere/filterbuilder/impl/SpatialFilterUtilities.java, open-sphere-plugins/kml/src/main/java/io/opensphere/kml/mantle/controller/KMLMantleController.java
Fixes VORTEX-6211
- ViewBookmarkUtil gains method to center the view, with options added to the view classed to more fully support centering on a target
- Spatial filter relevant code has been refactored into a utility class to allow access from more classes
=> VORTEX-6211 Missing options in right click menus of areas tab

open-sphere-base/analysis/src/main/java/io/opensphere/analysis/baseball/BaseballElementRow.java, open-sphere-base/control-panels/src/main/java/io/opensphere/controlpanels/layers/LayersFrame.java, open-sphere-base/control-panels/src/main/java/io/opensphere/controlpanels/layers/layerdetail/LayerDetailPanel.java, open-sphere-base/core/src/main/java/io/opensphere/core/appl/MenuInit.java, open-sphere-base/core/src/main/java/io/opensphere/core/map/MapManagerMenuProvider.java, open-sphere-base/core/src/main/java/io/opensphere/core/units/UnitsProvider.java, open-sphere-base/mantle/src/main/java/io/opensphere/mantle/data/geom/style/impl/ui/MultiComboEditor.java, open-sphere-base/overlay/src/main/java/io/opensphere/overlay/CursorPositionPanel.java, open-sphere-base/overlay/src/main/java/io/opensphere/overlay/CursorPositionPopupManager.java, open-sphere-base/overlay/src/main/java/io/opensphere/overlay/ViewerPositionTransformer.java, open-sphere-base/overlay/src/main/java/io/opensphere/overlay/scalebar/HUDScalebar.java, open-sphere-base/overlay/src/main/java/io/opensphere/overlay/terrainprofile/TerrainChartElevationLabel.java, open-sphere-plugins/feature-actions/src/main/java/io/opensphere/featureactions/editor/model/FeatureActionImporter.java, open-sphere-plugins/my-places/src/main/java/io/opensphere/myplaces/editor/controller/AnnotationsHelper.java, open-sphere-plugins/open-sensor-hub/src/main/java/io/opensphere/osh/aerialimagery/transformer/geometrybuilders/ImageGeometryBuilder.java, open-sphere-plugins/wms/src/main/java/io/opensphere/wms/state/BaseWmsStateController.java
Fixes #
Remove unused imports
-
-
-
=> Remove Unused Imports

open-sphere-plugins/feature-actions/src/main/java/io/opensphere/featureactions/FeatureActionsPlugin.java, open-sphere-plugins/feature-actions/src/main/java/io/opensphere/featureactions/registry/FeatureActionsRegistry.java, open-sphere-plugins/feature-actions/src/test/java/io/opensphere/featureactions/FeatureActionsPluginTest.java
Fixes VORTEX-6209
- options to clear feature actions (delete all existing feature actions) added to clear dropdown
=> VORTEX-6209 Add clear feature actions option to clear button

open-sphere-plugins/feature-actions/src/main/java/io/opensphere/featureactions/FeatureActionsPlugin.java, open-sphere-plugins/feature-actions/src/main/java/io/opensphere/featureactions/editor/ui/FeatureActionPanel.java, open-sphere-plugins/feature-actions/src/test/java/io/opensphere/featureactions/FeatureActionsPluginTest.java
Fixes VORTEX-6210
- new button along bottom toolbar opens feature action manager
- feature action manager allows customization of all layers in one window
=> VORTEX-6210 Add a feature actions manager to bottom of window

open-sphere-plugins/feature-actions/src/main/java/io/opensphere/featureactions/editor/ui/FeatureActionPanel.java
Fixes
- fix bug that would cause save button to sometimes resize by adding text to the button
=> Feature actions manager bugfix

Jenkinsfile
=> update jenkins param

pom.xml
Fixes # 
Update Apache Commons Compress to 1.19
-
-
-
=> Update Apache Commons Compress to 1.19

open-sphere-plugins/csv-common/src/main/java/io/opensphere/csvcommon/detect/columnformat/ColumnDelimiterDetector.java, open-sphere-plugins/csv-common/src/main/java/io/opensphere/csvcommon/detect/location/algorithm/MGRSMatchMaker.java
Fixes VORTEX-6284
- additional string length check added to handle case where the string is in three "parts" but still has a length < 2
=> VORTEX-6284 Importing specific CSV file causes importer to break

open-sphere-install/open-sphere-install-windows64/src/main/resources/scripts/launch.bat
=> DESKTOP-5 MIST Desktop can't use vb script anymore

open-sphere-base/core/src/main/java/io/opensphere/core/appl/versions/InstallDescriptorGenerator.java, open-sphere-base/core/src/test/java/io/opensphere/core/appl/AutoUpdateDemoServer.java
=> Feature auto update launcher

open-sphere-base/analysis/pom.xml, open-sphere-base/analysis/src/main/java/io/opensphere/analysis/baseball/BaseballController.java, open-sphere-base/analysis/src/main/java/io/opensphere/analysis/baseball/BaseballPanel.java, open-sphere-base/overlay/src/main/java/io/opensphere/overlay/CursorPositionTransformer.java, open-sphere-base/overlay/src/main/java/io/opensphere/overlay/OverlayListenerHelper.java, open-sphere-base/overlay/src/main/java/io/opensphere/overlay/util/MousePositionUtils.java
Fixes VORTEX-6293
- Features are grabbed around the mouse cursor when opening the baseball card
- Utility class added related to the mouse position on globe
- Cleaned up some formatting
=> VORTEX-6293 Error on baseball card

Jenkinsfile
=> changed maven in Jenkinsfile to Maven363

Jenkinsfile
=> changed maven to Maven362

Jenkinsfile, pom.xml
Fixes 
- enforced error-only mode for Maven commands run in Jenkins
- update jaxb2-maven-plugin version
=> DESKTOP-23/DESKTOP-32 Build output and jaxb2-maven-plugin
